# Generated by Django 5.2.17 on 2026-09-07 08:01

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomsOrder',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.PositiveIntegerField(unique=True, verbose_name='Номер заказа')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('fx_rate', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс USD/RUB')),
                ('total_quantity', models.DecimalField(decimal_places=3, default=Decimal('0'), max_digits=14, verbose_name='Количество')),
                ('total_rub', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=16, verbose_name='Сумма, ₽')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CustomsOrderLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('sale', 'Продажа'), ('repair', 'Ремонт'), ('ordered', 'Запчасть на заказ')], max_length=20)),
                ('source_id', models.PositiveBigIntegerField()),
                ('article', models.CharField(blank=True, max_length=100)),
                ('name_ru', models.CharField(blank=True, max_length=255)),
                ('name_en', models.CharField(blank=True, max_length=255)),
                ('manufacturer', models.CharField(blank=True, max_length=150)),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=14)),
                ('wholesale_usd', models.DecimalField(decimal_places=4, max_digits=14)),
                ('rub_amount', models.DecimalField(decimal_places=2, max_digits=16)),
                ('is_analog', models.BooleanField(default=False)),
                ('is_ordered', models.BooleanField(default=False)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lines', to='customs_orders.customsorder')),
            ],
            options={
                'ordering': ['pk'],
                'constraints': [models.UniqueConstraint(fields=('source', 'source_id'), name='customs_order_line_unique_source')],
            },
        ),
    ]
