# Generated by Django 5.2.17 on 2026-09-07 08:48

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_orders', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customsorderline',
            name='application_area',
            field=models.CharField(blank=True, max_length=120),
        ),
        migrations.AddField(
            model_name='customsorderline',
            name='country',
            field=models.CharField(blank=True, max_length=150),
        ),
        migrations.AddField(
            model_name='customsorderline',
            name='gross_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customsorderline',
            name='net_weight_kg',
            field=models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True),
        ),
        migrations.AddField(
            model_name='customsorderline',
            name='occurred_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddConstraint(
            model_name='customsorder',
            constraint=models.CheckConstraint(condition=models.Q(('number__gt', 0)), name='customs_order_number_gt0'),
        ),
        migrations.AddConstraint(
            model_name='customsorder',
            constraint=models.CheckConstraint(condition=models.Q(('fx_rate__gt', 0)), name='customs_order_fx_gt0'),
        ),
        migrations.AddConstraint(
            model_name='customsorderline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='customs_line_qty_gt0'),
        ),
        migrations.AddConstraint(
            model_name='customsorderline',
            constraint=models.CheckConstraint(condition=models.Q(('source__in', ['sale', 'repair', 'ordered'])), name='customs_line_valid_source'),
        ),
    ]
