# Generated by Django 5.2.17 on 2026-09-07 14:19

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customs_orders', '0002_customsorderline_application_area_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customsorder',
            name='order_type',
            field=models.CharField(choices=[('original', 'Оригиналы'), ('analog', 'Аналоги')], default='original', max_length=20, verbose_name='Тип заказа'),
        ),
        migrations.AlterField(
            model_name='customsorder',
            name='number',
            field=models.PositiveIntegerField(verbose_name='Номер заказа'),
        ),
        migrations.AddConstraint(
            model_name='customsorder',
            constraint=models.UniqueConstraint(fields=('order_type', 'number'), name='customs_order_unique_type_number'),
        ),
    ]
