# Generated by Django 5.2.17 on 2026-09-14 05:05

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_parttype_certified_price'),
        ('customs_orders', '0003_order_type_series'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customsorder',
            name='finalized_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='customsorder',
            name='finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='finalized_customs_orders', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='customsorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('finalized', 'Зафиксирован')], default='finalized', max_length=12),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='customsorder',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('finalized', 'Зафиксирован')], default='draft', max_length=12),
        ),
        migrations.AddField(
            model_name='customsorderline',
            name='part_type',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customs_order_lines', to='catalog.parttype'),
        ),
    ]
