# Generated by Django 5.2.15 on 2026-07-17 13:17

from django.db import migrations, models


def create_runtime_gate(apps, schema_editor):
    apps.get_model("ai_support", "SupportRuntimeGate").objects.create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('ai_support', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='SupportRuntimeGate',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
        ),
        migrations.RunPython(create_runtime_gate, migrations.RunPython.noop),
    ]
