# Generated by Django 5.2.15 on 2026-06-25 16:49

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_parttype_partnumber_partbarcode_partcompatibility'),
        ('inventory', '0004_alter_stocklot_status_stockbalance_stockmovement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Reservation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('active', 'Активен'), ('canceled', 'Отменён'), ('expired', 'Просрочен'), ('converted_to_sale', 'Продан')], default='draft', max_length=20, verbose_name='Статус')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Действует до')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыт (когда)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Резерв',
                'verbose_name_plural': 'Резервы',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='ReservationLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('part_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_lines', to='inventory.partitem', verbose_name='Экземпляр')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.parttype', verbose_name='Деталь')),
                ('reservation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.reservation', verbose_name='Резерв')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='reservation_lines', to='inventory.stocklot', verbose_name='Лот')),
            ],
            options={
                'verbose_name': 'Позиция резерва',
                'verbose_name_plural': 'Позиции резерва',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('part_item__isnull', False), ('stock_lot__isnull', True)), models.Q(('part_item__isnull', True), ('stock_lot__isnull', False)), _connector='OR'), name='reservationline_item_xor_lot'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='reservationline_qty_positive')],
            },
        ),
    ]
