# Generated by Django 5.2.15 on 2026-06-25 17:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_parttype_partnumber_partbarcode_partcompatibility'),
        ('inventory', '0005_alter_stockmovement_movement_type'),
        ('procurement', '0002_landed_cost'),
        ('sales', '0002_seed_reservation_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Sale',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Проведена'), ('canceled', 'Отменена'), ('voided', 'Сторнирована')], default='draft', max_length=20, verbose_name='Статус')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Клиент')),
                ('customer_phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('sold_at', models.DateTimeField(blank=True, null=True, verbose_name='Проведена (когда)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Закрыта (когда)')),
                ('revenue_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Выручка (₽)')),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Себестоимость (₽)')),
                ('profit_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Прибыль (₽)')),
                ('reservation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='sales', to='sales.reservation', verbose_name='Из резерва')),
                ('sold_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто провёл')),
            ],
            options={
                'verbose_name': 'Продажа',
                'verbose_name_plural': 'Продажи',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='SaleLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('unit_price', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за ед. (₽)')),
                ('total_price', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма (₽)')),
                ('unit_cost_rub', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Себестоимость за ед. (₽)')),
                ('total_cost_rub', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Себестоимость строки (₽)')),
                ('profit_rub', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Прибыль (₽)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='procurement.batch', verbose_name='Партия')),
                ('batch_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='procurement.batchline', verbose_name='Строка партии')),
                ('part_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='inventory.partitem', verbose_name='Экземпляр')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.parttype', verbose_name='Деталь')),
                ('sale', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='sales.sale', verbose_name='Продажа')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='sale_lines', to='inventory.stocklot', verbose_name='Лот')),
            ],
            options={
                'verbose_name': 'Позиция продажи',
                'verbose_name_plural': 'Позиции продажи',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('part_item__isnull', False), ('stock_lot__isnull', True)), models.Q(('part_item__isnull', True), ('stock_lot__isnull', False)), _connector='OR'), name='saleline_item_xor_lot'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='saleline_qty_positive')],
            },
        ),
    ]
