# Generated by Django 5.2.15 on 2026-08-13 20:52

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('sales', '0004_seed_sale_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='reservation',
            name='customer_phone_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, verbose_name='Телефон для поиска'),
        ),
        migrations.AddField(
            model_name='sale',
            name='customer_phone_normalized',
            field=models.CharField(blank=True, db_index=True, editable=False, max_length=50, verbose_name='Телефон для поиска'),
        ),
    ]
