# Generated by Django 5.2.17 on 2026-09-24 10:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("sales", "0007_saleline_unmarked_price_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="saleline",
            name="oil_package_price_rub_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="Цена упаковки (снимок, ₽)",
            ),
        ),
        migrations.AddField(
            model_name="saleline",
            name="oil_package_volume_l_snapshot",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                editable=False,
                max_digits=8,
                null=True,
                verbose_name="Объём упаковки (снимок, л)",
            ),
        ),
    ]
