# Generated by Django 5.2.17 on 2026-09-10 18:46

import django.db.models.deletion
import uuid
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0007_search_trigram'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequest',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(db_index=True, default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('canceled', 'Отменена')], default='new', max_length=20, verbose_name='Статус')),
                ('source', models.CharField(choices=[('public_catalog', 'Публичный каталог')], default='public_catalog', max_length=30, verbose_name='Источник')),
                ('customer_name', models.CharField(max_length=255, verbose_name='Имя')),
                ('customer_phone', models.CharField(max_length=50, verbose_name='Телефон')),
                ('customer_phone_normalized', models.CharField(db_index=True, editable=False, max_length=50, verbose_name='Телефон для поиска')),
                ('preferred_messenger', models.CharField(choices=[('telegram', 'Telegram'), ('max', 'MAX')], max_length=12, verbose_name='Предпочтительный мессенджер')),
                ('comment', models.TextField(blank=True, max_length=2000, verbose_name='Комментарий')),
                ('privacy_policy_version', models.CharField(max_length=64, verbose_name='Версия политики')),
                ('personal_data_consent_version', models.CharField(max_length=64, verbose_name='Версия согласия')),
                ('consent_purpose', models.CharField(max_length=120, verbose_name='Цель согласия')),
                ('consent_accepted_at', models.DateTimeField(verbose_name='Согласие принято')),
                ('consent_withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='Согласие отозвано')),
                ('data_anonymized_at', models.DateTimeField(blank=True, null=True, verbose_name='Данные обезличены')),
                ('submission_key_hash', models.CharField(max_length=64, unique=True, verbose_name='Ключ идемпотентности')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Заявка клиента',
                'verbose_name_plural': 'Заявки клиентов',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRequestLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_requested', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Запрошено')),
                ('unit_name', models.CharField(max_length=50, verbose_name='Единица (снимок)')),
                ('unit_short_name', models.CharField(max_length=20, verbose_name='Единица (сокращение, снимок)')),
                ('price_seen', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Цена на момент заявки (₽)')),
                ('article', models.CharField(blank=True, max_length=100, verbose_name='Артикул (снимок)')),
                ('part_name', models.CharField(max_length=200, verbose_name='Название (снимок)')),
                ('is_supply_inquiry', models.BooleanField(default=False, verbose_name='Запрос о поставке')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customer_requests', to='catalog.parttype', verbose_name='Деталь')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='customer_requests.customerrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Позиция заявки',
                'verbose_name_plural': 'Позиции заявки',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='CustomerRequestStatusEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('from_status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('canceled', 'Отменена')], max_length=20, verbose_name='Статус до')),
                ('to_status', models.CharField(choices=[('new', 'Новая'), ('in_progress', 'В работе'), ('completed', 'Выполнена'), ('canceled', 'Отменена')], max_length=20, verbose_name='Статус после')),
                ('changed_at', models.DateTimeField(auto_now_add=True, verbose_name='Изменён')),
                ('changed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='status_events', to='customer_requests.customerrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Изменение статуса заявки',
                'verbose_name_plural': 'Изменения статуса заявок',
                'ordering': ['-changed_at', '-pk'],
            },
        ),
        migrations.AddIndex(
            model_name='customerrequest',
            index=models.Index(fields=['status', '-created_at'], name='custreq_status_created_idx'),
        ),
        migrations.AddConstraint(
            model_name='customerrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity_requested__gt', Decimal('0'))), name='custreq_line_quantity_positive'),
        ),
        migrations.AddConstraint(
            model_name='customerrequestline',
            constraint=models.CheckConstraint(condition=models.Q(('price_seen__isnull', True), ('price_seen__gte', Decimal('0')), _connector='OR'), name='custreq_line_price_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='customerrequestline',
            constraint=models.UniqueConstraint(fields=('request', 'part_type'), name='custreq_line_part_unique'),
        ),
    ]
