# Generated by Django 5.2.17 on 2026-09-10 18:53

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_requests', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequestMessengerContact',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram')], max_length=12, verbose_name='Канал')),
                ('remote_chat_id', models.CharField(max_length=64, verbose_name='Идентификатор чата')),
                ('linked_at', models.DateTimeField(auto_now_add=True, verbose_name='Связан')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_contact', to='customer_requests.customerrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Контакт заявки в мессенджере',
                'verbose_name_plural': 'Контакты заявок в мессенджерах',
                'constraints': [models.UniqueConstraint(fields=('channel', 'remote_chat_id'), name='custreq_contact_channel_chat_unique')],
            },
        ),
        migrations.CreateModel(
            name='CustomerRequestMessengerLinkToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('channel', models.CharField(choices=[('telegram', 'Telegram')], max_length=12, verbose_name='Канал')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='Хеш токена')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('expires_at', models.DateTimeField(verbose_name='Действует до')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозван')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messenger_link_tokens', to='customer_requests.customerrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Ссылка заявки в мессенджер',
                'verbose_name_plural': 'Ссылки заявок в мессенджеры',
                'indexes': [models.Index(fields=['channel', 'expires_at'], name='custreq_link_channel_exp_idx')],
            },
        ),
    ]
