# Generated by Django 5.2.17 on 2026-09-11 03:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_requests', '0002_telegram_link'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customerrequestmessengercontact',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('max', 'MAX')], max_length=12, verbose_name='Канал'),
        ),
        migrations.AlterField(
            model_name='customerrequestmessengerlinktoken',
            name='channel',
            field=models.CharField(choices=[('telegram', 'Telegram'), ('max', 'MAX')], max_length=12, verbose_name='Канал'),
        ),
    ]
