# Generated by Django 5.2.17 on 2026-09-11 03:45

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_requests', '0003_max_channel'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerRequestPrivacyEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(choices=[('consent_withdrawn', 'Согласие отозвано'), ('anonymized', 'Данные обезличены')], max_length=24, verbose_name='Событие')),
                ('occurred_at', models.DateTimeField(auto_now_add=True, verbose_name='Произошло')),
                ('performed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто выполнил')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='privacy_events', to='customer_requests.customerrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Событие приватности заявки',
                'verbose_name_plural': 'События приватности заявок',
                'ordering': ['-occurred_at', '-pk'],
            },
        ),
    ]
