# Generated by Django 5.2.17 on 2026-09-14 16:35

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_requests', '0004_privacy_lifecycle'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('awaiting_link', 'Ожидает подключения'), ('linked', 'Telegram подключён'), ('closed', 'Закрыта')], default='awaiting_link', max_length=20, verbose_name='Состояние')),
                ('customer_chat_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='Чат клиента')),
                ('customer_user_id', models.BigIntegerField(blank=True, null=True, verbose_name='Telegram ID клиента')),
                ('customer_username', models.CharField(blank=True, max_length=64, verbose_name='Имя пользователя (снимок)')),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='Подключён')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
            ],
            options={
                'verbose_name': 'Переписка Telegram',
                'verbose_name_plural': 'Переписки Telegram',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='TelegramCustomerChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('chat_id', models.BigIntegerField(unique=True, verbose_name='Чат клиента')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Чат клиента Telegram',
                'verbose_name_plural': 'Чаты клиентов Telegram',
            },
        ),
        migrations.CreateModel(
            name='TelegramDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Получено'), ('pending', 'В очереди'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Не доставлено'), ('uncertain', 'Неизвестно, доставлено ли')], default='pending', max_length=12, verbose_name='Доставка')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Сообщение Telegram')),
                ('last_error', models.CharField(blank=True, max_length=255, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Уведомление сотрудника в Telegram',
                'verbose_name_plural': 'Уведомления сотрудников в Telegram',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='TelegramMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('customer_to_operator', 'Клиент'), ('operator_to_customer', 'Сотрудник'), ('system', 'Система')], max_length=24, verbose_name='Направление')),
                ('text', models.TextField(blank=True, max_length=4096, verbose_name='Текст')),
                ('delivery_status', models.CharField(choices=[('received', 'Получено'), ('pending', 'В очереди'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Не доставлено'), ('uncertain', 'Неизвестно, доставлено ли')], default='received', max_length=12, verbose_name='Доставка')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Сообщение Telegram')),
                ('telegram_update_id', models.BigIntegerField(blank=True, null=True, unique=True, verbose_name='Обновление Telegram')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка')),
                ('last_error', models.CharField(blank=True, max_length=255, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
            ],
            options={
                'verbose_name': 'Сообщение Telegram',
                'verbose_name_plural': 'Сообщения Telegram',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='TelegramOperator',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('telegram_user_id', models.BigIntegerField(unique=True, verbose_name='Telegram ID')),
                ('role', models.CharField(choices=[('admin', 'Администратор'), ('operator', 'Оператор')], default='operator', max_length=12, verbose_name='Роль')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('reply_started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начал ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
            ],
            options={
                'verbose_name': 'Сотрудник в Telegram-боте',
                'verbose_name_plural': 'Сотрудники в Telegram-боте',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='TelegramOutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('new_request', 'Новая заявка'), ('customer_linked', 'Клиент подключил Telegram'), ('customer_message', 'Сообщение клиента'), ('operator_reply', 'Ответ сотрудника')], max_length=24, verbose_name='Событие')),
                ('dedupe_key', models.CharField(max_length=120, unique=True, verbose_name='Ключ события')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассылки'), ('dispatched', 'Разослано сотрудникам'), ('expired', 'Истекло без сотрудников')], default='pending', max_length=12, verbose_name='Состояние')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='Разослано')),
            ],
            options={
                'verbose_name': 'Событие Telegram для сотрудников',
                'verbose_name_plural': 'События Telegram для сотрудников',
                'ordering': ['pk'],
            },
        ),
        migrations.RemoveConstraint(
            model_name='customerrequestmessengercontact',
            name='custreq_contact_channel_chat_unique',
        ),
        migrations.AddField(
            model_name='telegramconversation',
            name='request',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_conversation', to='customer_requests.customerrequest', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='telegramcustomerchat',
            name='active_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer_requests.telegramconversation', verbose_name='Активная переписка'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='conversation',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customer_requests.telegramconversation', verbose_name='Переписка'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='operator_user',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='telegramoperator',
            name='created_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил'),
        ),
        migrations.AddField(
            model_name='telegramoperator',
            name='reply_conversation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer_requests.telegramconversation', verbose_name='Отвечает на'),
        ),
        migrations.AddField(
            model_name='telegramoperator',
            name='user',
            field=models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='telegram_operator', to=settings.AUTH_USER_MODEL, verbose_name='Пользователь DenisStock'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='customer_requests.telegramoperator', verbose_name='Сотрудник в боте'),
        ),
        migrations.AddField(
            model_name='telegramdelivery',
            name='operator',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='customer_requests.telegramoperator', verbose_name='Сотрудник'),
        ),
        migrations.AddField(
            model_name='telegramoutboxevent',
            name='exclude_operator',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer_requests.telegramoperator', verbose_name='Не уведомлять'),
        ),
        migrations.AddField(
            model_name='telegramoutboxevent',
            name='message',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='customer_requests.telegrammessage', verbose_name='Сообщение'),
        ),
        migrations.AddField(
            model_name='telegramoutboxevent',
            name='request',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='telegram_events', to='customer_requests.customerrequest', verbose_name='Заявка'),
        ),
        migrations.AddField(
            model_name='telegramdelivery',
            name='event',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='customer_requests.telegramoutboxevent', verbose_name='Событие'),
        ),
        migrations.AddConstraint(
            model_name='telegramoperator',
            constraint=models.CheckConstraint(condition=models.Q(('telegram_user_id__gt', 0)), name='tg_operator_user_id_positive'),
        ),
        migrations.AddIndex(
            model_name='telegrammessage',
            index=models.Index(fields=['delivery_status', 'next_attempt_at'], name='tg_message_delivery_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramoutboxevent',
            index=models.Index(fields=['status', 'next_attempt_at'], name='tg_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='telegramdelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='tg_delivery_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='telegramdelivery',
            constraint=models.UniqueConstraint(fields=('event', 'operator'), name='tg_delivery_unique'),
        ),
    ]
