# Generated by Django 5.2.17 on 2026-09-16 14:13

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_requests', '0007_telegram_link_attempt_cap'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxConversation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('status', models.CharField(choices=[('awaiting_link', 'Ожидает подключения'), ('linked', 'MAX подключён'), ('closed', 'Закрыта')], default='awaiting_link', max_length=20, verbose_name='Состояние')),
                ('customer_user_id', models.BigIntegerField(blank=True, db_index=True, null=True, verbose_name='MAX ID клиента')),
                ('customer_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Диалог клиента')),
                ('linked_at', models.DateTimeField(blank=True, null=True, verbose_name='Подключён')),
                ('last_message_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее сообщение')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('request', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='max_conversation', to='customer_requests.customerrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Переписка MAX',
                'verbose_name_plural': 'Переписки MAX',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='MaxCustomerChat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('user_id', models.BigIntegerField(unique=True, verbose_name='MAX ID клиента')),
                ('chat_id', models.BigIntegerField(verbose_name='Диалог клиента')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('active_conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='customer_requests.maxconversation', verbose_name='Активная переписка')),
            ],
            options={
                'verbose_name': 'Клиент MAX',
                'verbose_name_plural': 'Клиенты MAX',
            },
        ),
        migrations.CreateModel(
            name='MaxMessage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('direction', models.CharField(choices=[('customer_to_operator', 'Клиент'), ('operator_to_customer', 'Сотрудник'), ('system', 'Система')], max_length=24, verbose_name='Направление')),
                ('text', models.TextField(blank=True, max_length=4000, verbose_name='Текст')),
                ('buttons', models.JSONField(blank=True, null=True, verbose_name='Кнопки')),
                ('delivery_status', models.CharField(choices=[('received', 'Получено'), ('pending', 'В очереди'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Не доставлено'), ('uncertain', 'Неизвестно, доставлено ли')], default='received', max_length=12, verbose_name='Доставка')),
                ('recipient_chat_id', models.BigIntegerField(blank=True, null=True, verbose_name='Диалог получателя')),
                ('external_message_id', models.CharField(blank=True, max_length=512, verbose_name='Сообщение MAX')),
                ('dedupe_key', models.CharField(blank=True, max_length=160, verbose_name='Ключ сообщения')),
                ('callback_id', models.CharField(blank=True, max_length=256, verbose_name='Нажатие кнопки')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка')),
                ('last_error', models.CharField(blank=True, max_length=255, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('conversation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='messages', to='customer_requests.maxconversation', verbose_name='Переписка')),
                ('operator_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
            ],
            options={
                'verbose_name': 'Сообщение MAX',
                'verbose_name_plural': 'Сообщения MAX',
                'ordering': ['created_at', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='MaxOutboxEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('new_request', 'Новая заявка'), ('customer_linked', 'Клиент подключил MAX'), ('customer_message', 'Сообщение клиента'), ('operator_reply', 'Ответ сотрудника')], max_length=24, verbose_name='Событие')),
                ('dedupe_key', models.CharField(max_length=120, unique=True, verbose_name='Ключ события')),
                ('status', models.CharField(choices=[('pending', 'Ожидает рассылки'), ('dispatched', 'Разослано сотрудникам'), ('expired', 'Истекло без сотрудников')], default='pending', max_length=12, verbose_name='Состояние')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('dispatched_at', models.DateTimeField(blank=True, null=True, verbose_name='Разослано')),
                ('exclude_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Не уведомлять')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='events', to='customer_requests.maxmessage', verbose_name='Сообщение')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='max_events', to='customer_requests.customerrequest', verbose_name='Заявка')),
            ],
            options={
                'verbose_name': 'Событие MAX для сотрудников',
                'verbose_name_plural': 'События MAX для сотрудников',
                'ordering': ['pk'],
            },
        ),
        migrations.CreateModel(
            name='MaxOperatorDelivery',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('status', models.CharField(choices=[('received', 'Получено'), ('pending', 'В очереди'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Не доставлено'), ('uncertain', 'Неизвестно, доставлено ли')], default='pending', max_length=12, verbose_name='Доставка')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка')),
                ('telegram_message_id', models.BigIntegerField(blank=True, null=True, verbose_name='Сообщение в боте')),
                ('last_error', models.CharField(blank=True, max_length=255, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('recipient', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник')),
                ('event', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='deliveries', to='customer_requests.maxoutboxevent', verbose_name='Событие')),
            ],
            options={
                'verbose_name': 'Уведомление сотрудника о MAX',
                'verbose_name_plural': 'Уведомления сотрудников о MAX',
                'ordering': ['pk'],
            },
        ),
        migrations.AddConstraint(
            model_name='maxconversation',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'linked'), _negated=True), models.Q(('customer_user_id__isnull', False), ('customer_chat_id__isnull', False)), _connector='OR'), name='max_conversation_linked_identity'),
        ),
        migrations.AddIndex(
            model_name='maxmessage',
            index=models.Index(fields=['delivery_status', 'next_attempt_at'], name='max_message_delivery_idx'),
        ),
        migrations.AddConstraint(
            model_name='maxmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('direction', 'customer_to_operator')), fields=('external_message_id',), name='max_message_inbound_mid_unique'),
        ),
        migrations.AddConstraint(
            model_name='maxmessage',
            constraint=models.UniqueConstraint(condition=models.Q(('dedupe_key', ''), _negated=True), fields=('dedupe_key',), name='max_message_dedupe_unique'),
        ),
        migrations.AddConstraint(
            model_name='maxmessage',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('direction', 'customer_to_operator'), _negated=True), models.Q(('conversation__isnull', False), models.Q(('external_message_id', ''), _negated=True)), _connector='OR'), name='max_message_inbound_has_identity'),
        ),
        migrations.AddConstraint(
            model_name='maxmessage',
            constraint=models.CheckConstraint(condition=models.Q(('direction', 'customer_to_operator'), ('recipient_chat_id__isnull', False), _connector='OR'), name='max_message_outbound_has_recipient'),
        ),
        migrations.AddIndex(
            model_name='maxoutboxevent',
            index=models.Index(fields=['status', 'next_attempt_at'], name='max_event_status_idx'),
        ),
        migrations.AddIndex(
            model_name='maxoperatordelivery',
            index=models.Index(fields=['status', 'next_attempt_at'], name='max_delivery_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='maxoperatordelivery',
            constraint=models.UniqueConstraint(fields=('event', 'recipient'), name='max_delivery_unique'),
        ),
    ]
