# Generated by Django 5.2.17 on 2026-09-19 14:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_requests', '0011_realtime_workspace'),
    ]

    operations = [
        migrations.AddField(
            model_name='maxmessage',
            name='attachment',
            field=models.FileField(blank=True, upload_to='customer_requests/', verbose_name='Вложение'),
        ),
        migrations.AddField(
            model_name='maxmessage',
            name='attachment_content_type',
            field=models.CharField(blank=True, max_length=80, verbose_name='Тип вложения'),
        ),
        migrations.AddField(
            model_name='maxmessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Имя вложения'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='attachment',
            field=models.FileField(blank=True, upload_to='customer_requests/', verbose_name='Вложение'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='attachment_content_type',
            field=models.CharField(blank=True, max_length=80, verbose_name='Тип вложения'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='attachment_name',
            field=models.CharField(blank=True, max_length=180, verbose_name='Имя вложения'),
        ),
    ]
