# Generated by Django 5.2.17 on 2026-09-19 15:38

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_accounts', '0001_initial'),
        ('customer_requests', '0014_maxmessage_attachment_token'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='customer_account',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='requests', to='customer_accounts.customeraccount', verbose_name='Кабинет клиента'),
        ),
    ]
