# Generated by Django 5.2.17 on 2026-09-20 20:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_requests', '0016_messenger_repeat_source'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OperatorConsoleRuntime',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('singleton', models.BooleanField(default=True, editable=False, unique=True)),
                ('announce_requests_since', models.DateTimeField(blank=True, null=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Состояние мобильной консоли',
                'verbose_name_plural': 'Состояние мобильной консоли',
            },
        ),
        migrations.AddField(
            model_name='maxmessage',
            name='operator_author_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='Подпись сотрудника'),
        ),
        migrations.AddField(
            model_name='maxmessage',
            name='operator_control_source',
            field=models.CharField(blank=True, max_length=12, verbose_name='Канал управления'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='operator_author_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='Подпись сотрудника'),
        ),
        migrations.AddField(
            model_name='telegrammessage',
            name='operator_control_source',
            field=models.CharField(blank=True, max_length=12, verbose_name='Канал управления'),
        ),
        migrations.CreateModel(
            name='StaffMessengerBinding',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('telegram', 'Telegram'), ('max', 'MAX')], max_length=12, verbose_name='Мессенджер')),
                ('provider_user_id', models.BigIntegerField(verbose_name='ID пользователя мессенджера')),
                ('customer_visible_label', models.CharField(max_length=80, verbose_name='Подпись для клиента')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активна')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлена')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_messenger_bindings', to=settings.AUTH_USER_MODEL, verbose_name='Кто привязал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_messenger_bindings', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник DenisStock')),
            ],
            options={
                'verbose_name': 'Привязка сотрудника к мессенджеру',
                'verbose_name_plural': 'Привязки сотрудников к мессенджерам',
            },
        ),
        migrations.CreateModel(
            name='OperatorNotification',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('new_request', 'Новая заявка'), ('customer_message', 'Сообщение клиента')], max_length=24, verbose_name='Событие')),
                ('dedupe_key', models.CharField(max_length=180, unique=True, verbose_name='Ключ идемпотентности')),
                ('preview', models.CharField(blank=True, max_length=700, verbose_name='Краткий текст')),
                ('status', models.CharField(choices=[('pending', 'В очереди'), ('sending', 'Отправляется'), ('sent', 'Отправлено'), ('failed', 'Не доставлено'), ('uncertain', 'Неизвестно, доставлено ли')], default='pending', max_length=12, verbose_name='Состояние')),
                ('attempts', models.PositiveSmallIntegerField(default=0, verbose_name='Попыток')),
                ('next_attempt_at', models.DateTimeField(blank=True, null=True, verbose_name='Следующая попытка')),
                ('external_message_id', models.CharField(blank=True, max_length=512, verbose_name='Внешний ID')),
                ('last_error', models.CharField(blank=True, max_length=255, verbose_name='Последняя ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создано')),
                ('sent_at', models.DateTimeField(blank=True, null=True, verbose_name='Отправлено')),
                ('request', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='operator_notifications', to='customer_requests.customerrequest', verbose_name='Заявка')),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='notifications', to='customer_requests.staffmessengerbinding', verbose_name='Привязка')),
            ],
            options={
                'verbose_name': 'Уведомление мобильной консоли',
                'verbose_name_plural': 'Уведомления мобильной консоли',
            },
        ),
        migrations.CreateModel(
            name='OperatorConversationContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('request', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='operator_contexts', to='customer_requests.customerrequest', verbose_name='Активная заявка')),
                ('binding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='context', to='customer_requests.staffmessengerbinding', verbose_name='Привязка')),
            ],
        ),
        migrations.CreateModel(
            name='StaffMessengerPairingToken',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(max_length=64, unique=True, verbose_name='Хеш токена')),
                ('provider', models.CharField(choices=[('telegram', 'Telegram'), ('max', 'MAX')], max_length=12, verbose_name='Мессенджер')),
                ('customer_visible_label', models.CharField(max_length=80, verbose_name='Подпись для клиента')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('used_at', models.DateTimeField(blank=True, null=True, verbose_name='Использован')),
                ('revoked_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозван')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='created_staff_pairing_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='staff_pairing_tokens', to=settings.AUTH_USER_MODEL, verbose_name='Сотрудник DenisStock')),
            ],
            options={
                'verbose_name': 'Одноразовый код привязки сотрудника',
                'verbose_name_plural': 'Одноразовые коды привязки сотрудников',
            },
        ),
        migrations.AddIndex(
            model_name='staffmessengerbinding',
            index=models.Index(fields=['provider', 'is_active'], name='staff_binding_active_idx'),
        ),
        migrations.AddConstraint(
            model_name='staffmessengerbinding',
            constraint=models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='staff_binding_provider_user_unique'),
        ),
        migrations.AddConstraint(
            model_name='staffmessengerbinding',
            constraint=models.UniqueConstraint(fields=('user', 'provider'), name='staff_binding_user_provider_unique'),
        ),
        migrations.AddConstraint(
            model_name='staffmessengerbinding',
            constraint=models.CheckConstraint(condition=models.Q(('provider_user_id__gt', 0)), name='staff_binding_provider_id_positive'),
        ),
        migrations.AddIndex(
            model_name='operatornotification',
            index=models.Index(fields=['binding', 'status', 'next_attempt_at'], name='operator_notif_due_idx'),
        ),
        migrations.AddConstraint(
            model_name='operatornotification',
            constraint=models.UniqueConstraint(fields=('binding', 'request', 'kind', 'dedupe_key'), name='operator_notification_identity_unique'),
        ),
        migrations.AddIndex(
            model_name='staffmessengerpairingtoken',
            index=models.Index(fields=['provider', 'expires_at'], name='staff_pairing_exp_idx'),
        ),
    ]
