# Generated by Django 5.2.17 on 2026-09-20 20:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_requests', '0017_operatorconsoleruntime_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='staffmessengerbinding',
            name='operator_mode',
            field=models.BooleanField(default=False, verbose_name='Рабочий режим'),
        ),
    ]
