# Generated by Django 5.2.17 on 2026-09-20 20:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_requests', '0018_staffmessengerbinding_operator_mode'),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='current_responder_control_source',
            field=models.CharField(blank=True, max_length=12, verbose_name='Канал текущего ответственного'),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='current_responder_label',
            field=models.CharField(blank=True, max_length=80, verbose_name='Текущий ответственный'),
        ),
    ]
