# Generated by Django 5.2.17 on 2026-09-22 19:09

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0018_partphotouploadaudit'),
        ('customer_requests', '0024_alter_operatornotification_kind'),
    ]

    operations = [
        migrations.CreateModel(
            name='OwnerPhotoUploadContext',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('operation_type', models.CharField(max_length=12, verbose_name='Тип операции')),
                ('operation_id', models.PositiveBigIntegerField(verbose_name='Операция')),
                ('article_snapshot', models.CharField(blank=True, max_length=100, verbose_name='Артикул (снимок)')),
                ('part_name_snapshot', models.CharField(max_length=200, verbose_name='Название (снимок)')),
                ('expires_at', models.DateTimeField(verbose_name='Истекает')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('binding', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='photo_upload_context', to='customer_requests.staffmessengerbinding', verbose_name='Привязка владельца')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='owner_photo_contexts', to='catalog.parttype', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Контекст загрузки фото владельца',
                'verbose_name_plural': 'Контексты загрузки фото владельца',
                'indexes': [models.Index(fields=['expires_at'], name='owner_photo_ctx_exp_idx')],
            },
        ),
        migrations.CreateModel(
            name='OwnerPhotoUploadReceipt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('external_id', models.CharField(max_length=160, verbose_name='Идентификатор обновления')),
                ('response_text', models.TextField(verbose_name='Ответ')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('binding', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='photo_upload_receipts', to='customer_requests.staffmessengerbinding', verbose_name='Привязка владельца')),
                ('part_type', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='owner_photo_receipts', to='catalog.parttype', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Квитанция загрузки фото владельца',
                'verbose_name_plural': 'Квитанции загрузки фото владельца',
                'constraints': [models.UniqueConstraint(fields=('binding', 'external_id'), name='owner_photo_receipt_unique')],
            },
        ),
    ]
