# Generated by Django 5.2.17 on 2026-09-23 17:46

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customer_requests', '0025_ownerphotouploadcontext_ownerphotouploadreceipt'),
        ('customers', '0004_customercreateidempotency'),
        ('sales', '0007_saleline_unmarked_price_snapshot'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='customerrequest',
            name='customer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_requests', to='customers.customer', verbose_name='Карточка клиента'),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='sale',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='customer_request', to='sales.sale', verbose_name='Продажа по заявке'),
        ),
        migrations.AddField(
            model_name='customerrequest',
            name='taken_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='taken_customer_requests', to=settings.AUTH_USER_MODEL, verbose_name='Взял в работу'),
        ),
    ]
