# Generated by Django 5.2.15 on 2026-08-13 22:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Customer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='Имя клиента')),
                ('phone', models.CharField(blank=True, max_length=50, verbose_name='Телефон')),
                ('phone_normalized', models.CharField(blank=True, db_index=True, editable=False, max_length=50, verbose_name='Телефон для поиска')),
                ('comment', models.TextField(blank=True, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Клиент',
                'verbose_name_plural': 'Клиенты',
                'ordering': ['name', 'pk'],
                'indexes': [models.Index(fields=['name'], name='customer_name_idx')],
            },
        ),
    ]
