# Generated by Django 5.2.12 on 2026-08-26

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("customers", "0001_initial"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerPeriodPaymentAcknowledgement",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("period_start", models.DateField(verbose_name="Период с")),
                ("period_end", models.DateField(verbose_name="Период по")),
                ("amount_rub", models.DecimalField(decimal_places=2, max_digits=14, verbose_name="Подтверждённая сумма (₽)")),
                ("billable_fingerprint", models.CharField(max_length=64, verbose_name="Снимок состава начислений")),
                ("document_count", models.PositiveIntegerField(verbose_name="Количество документов")),
                ("acknowledged_at", models.DateTimeField(auto_now_add=True, verbose_name="Подтверждено когда")),
                ("revoked_at", models.DateTimeField(blank=True, null=True, verbose_name="Снято когда")),
                ("acknowledged_by", models.ForeignKey(null=True, on_delete=models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Подтвердил")),
                ("customer", models.ForeignKey(on_delete=models.deletion.PROTECT, related_name="payment_acknowledgements", to="customers.customer", verbose_name="Клиент")),
                ("revoked_by", models.ForeignKey(blank=True, null=True, on_delete=models.deletion.SET_NULL, related_name="+", to=settings.AUTH_USER_MODEL, verbose_name="Снял")),
            ],
            options={
                "verbose_name": "Подтверждение оплаты клиента за период",
                "verbose_name_plural": "Подтверждения оплаты клиентов за период",
                "ordering": ["-acknowledged_at", "-pk"],
            },
        ),
        migrations.AddIndex(
            model_name="customerperiodpaymentacknowledgement",
            index=models.Index(fields=["customer", "period_start", "period_end", "revoked_at"], name="customer_period_payment_idx"),
        ),
        migrations.AddConstraint(
            model_name="customerperiodpaymentacknowledgement",
            constraint=models.CheckConstraint(condition=models.Q(("period_end__gte", models.F("period_start"))), name="customer_payment_period_ordered"),
        ),
    ]
