# Generated by Django 5.2.17 on 2026-09-14 10:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0002_customerperiodpaymentacknowledgement'),
    ]

    operations = [
        migrations.AddField(
            model_name='customer',
            name='city',
            field=models.CharField(blank=True, max_length=150, verbose_name='Город'),
        ),
        migrations.AddField(
            model_name='customer',
            name='equipment',
            field=models.CharField(blank=True, max_length=255, verbose_name='Техника'),
        ),
        migrations.AddField(
            model_name='customer',
            name='mileage_at_arrival',
            field=models.PositiveIntegerField(blank=True, null=True, verbose_name='Пробег'),
        ),
        migrations.AddField(
            model_name='customer',
            name='vin',
            field=models.CharField(blank=True, max_length=100, verbose_name='VIN'),
        ),
    ]
