# Generated by Django 5.2.17 on 2026-09-21 15:24

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('customers', '0003_customer_city_customer_equipment_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerCreateIdempotency',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.UUIDField(editable=False, unique=True, verbose_name='Ключ создания')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('customer', models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='create_idempotency_receipt', to='customers.customer', verbose_name='Созданный клиент')),
            ],
            options={
                'verbose_name': 'Квитанция идемпотентности создания клиента',
                'verbose_name_plural': 'Квитанции идемпотентности создания клиентов',
            },
        ),
    ]
