# Generated by Django 5.2.17 on 2026-09-24 18:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("customers", "0004_customercreateidempotency"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="CustomerMergeReceipt",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "normalized_phone",
                    models.CharField(
                        blank=True,
                        max_length=50,
                        verbose_name="Канонический телефон (снимок)",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Когда"),
                ),
                (
                    "moved_counts",
                    models.JSONField(default=dict, verbose_name="Перенесённые связи"),
                ),
                (
                    "reason",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Причина / комментарий"
                    ),
                ),
            ],
            options={
                "verbose_name": "Квитанция объединения клиентов",
                "verbose_name_plural": "Квитанции объединения клиентов",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.AddField(
            model_name="customer",
            name="merged_into",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merged_from",
                to="customers.customer",
                verbose_name="Объединена с карточкой",
            ),
        ),
        migrations.AddConstraint(
            model_name="customer",
            constraint=models.CheckConstraint(
                condition=models.Q(("merged_into", models.F("id")), _negated=True),
                name="customer_merged_into_not_self",
            ),
        ),
        migrations.AddField(
            model_name="customermergereceipt",
            name="performed_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто выполнил",
            ),
        ),
        migrations.AddField(
            model_name="customermergereceipt",
            name="source",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merge_receipts_as_source",
                to="customers.customer",
                verbose_name="Источник",
            ),
        ),
        migrations.AddField(
            model_name="customermergereceipt",
            name="target",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.PROTECT,
                related_name="merge_receipts_as_target",
                to="customers.customer",
                verbose_name="Куда объединили",
            ),
        ),
    ]
