# Generated by Django 5.2.15 on 2026-06-24 10:39

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_parttype_partnumber_partbarcode_partcompatibility'),
        ('suppliers', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Batch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(blank=True, max_length=20, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('draft', 'Создана'), ('ordered', 'Заказана'), ('in_transit', 'В пути'), ('arrived', 'Прибыла'), ('receiving', 'Принимается'), ('accepted', 'Принята'), ('cost_calculated', 'Себестоимость рассчитана'), ('closed', 'Закрыта'), ('canceled', 'Отменена')], default='draft', max_length=20, verbose_name='Статус')),
                ('country', models.CharField(blank=True, max_length=100, verbose_name='Страна')),
                ('currency', models.CharField(default='RUB', max_length=3, verbose_name='Валюта')),
                ('exchange_rate', models.DecimalField(decimal_places=4, default=1, max_digits=12, verbose_name='Курс')),
                ('order_number', models.CharField(blank=True, max_length=100, verbose_name='Номер заказа')),
                ('invoice_number', models.CharField(blank=True, max_length=100, verbose_name='Номер счёта')),
                ('ordered_at', models.DateField(blank=True, null=True, verbose_name='Дата заказа')),
                ('shipped_at', models.DateField(blank=True, null=True, verbose_name='Дата отправки')),
                ('arrived_at', models.DateField(blank=True, null=True, verbose_name='Дата прибытия')),
                ('notes', models.TextField(blank=True, verbose_name='Комментарий')),
                ('cost_finalized', models.BooleanField(default=False, verbose_name='Себестоимость зафиксирована')),
                ('goods_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма товаров')),
                ('shipping_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Доставка')),
                ('customs_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Таможня')),
                ('commission_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Комиссии')),
                ('other_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Прочие расходы')),
                ('total_extra_cost', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма доп. расходов')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('supplier', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batches', to='suppliers.supplier', verbose_name='Поставщик')),
            ],
            options={
                'verbose_name': 'Партия',
                'verbose_name_plural': 'Партии',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='BatchLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('unit_cost_currency', models.DecimalField(decimal_places=2, max_digits=12, verbose_name='Цена за ед. (валюта)')),
                ('unit_cost_rub', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Цена за ед. (₽)')),
                ('total_cost_currency', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Итого (валюта)')),
                ('total_cost_rub', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Итого (₽)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='procurement.batch')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='batch_lines', to='catalog.parttype', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Строка поступления',
                'verbose_name_plural': 'Строки поступления',
                'ordering': ['id'],
            },
        ),
    ]
