# Generated by Django 5.2.15 on 2026-06-24 14:26

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('procurement', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='batch',
            name='cost_allocation_method',
            field=models.CharField(choices=[('by_value', 'По стоимости'), ('by_quantity', 'По количеству')], default='by_value', max_length=20, verbose_name='Метод распределения'),
        ),
        migrations.AddField(
            model_name='batch',
            name='cost_finalized_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Себестоимость зафиксирована (когда)'),
        ),
        migrations.AddField(
            model_name='batch',
            name='cost_finalized_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто зафиксировал'),
        ),
        migrations.AddField(
            model_name='batchline',
            name='allocated_overhead_rub',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Доля доп. расходов (₽)'),
        ),
        migrations.AddField(
            model_name='batchline',
            name='landed_total_cost_rub',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Себестоимость строки (₽)'),
        ),
        migrations.AddField(
            model_name='batchline',
            name='landed_unit_cost_rub',
            field=models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Себестоимость за ед. (₽)'),
        ),
    ]
