# Generated by Django 5.2.17 on 2026-09-19 15:38

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('customers', '0003_customer_city_customer_equipment_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CustomerAccount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('display_name', models.CharField(blank=True, db_default=models.Value(''), max_length=120, verbose_name='Имя')),
                ('status', models.CharField(choices=[('active', 'Активен'), ('deactivated', 'Деактивирован')], db_default=models.Value('active'), default='active', max_length=16, verbose_name='Состояние')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлён')),
                ('last_login_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний вход')),
                ('deactivated_at', models.DateTimeField(blank=True, null=True, verbose_name='Деактивирован')),
            ],
            options={
                'verbose_name': 'Кабинет клиента',
                'verbose_name_plural': 'Кабинеты клиентов',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CustomerAccountEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('kind', models.CharField(choices=[('created', 'Создан'), ('login', 'Вход'), ('logout', 'Выход'), ('identity_linked', 'Мессенджер подключён'), ('identity_unlinked', 'Мессенджер отключён'), ('requests_claimed', 'Заявки привязаны'), ('customer_linked', 'Карточка клиента привязана'), ('customer_unlinked', 'Карточка клиента отвязана'), ('consent_given', 'Согласие дано'), ('consent_withdrawn', 'Согласие отозвано'), ('profile_changed', 'Профиль изменён'), ('deactivated', 'Деактивирован')], max_length=32)),
                ('detail', models.JSONField(blank=True, default=dict)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer_accounts.customeraccount')),
                ('actor_user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Событие кабинета',
                'verbose_name_plural': 'События кабинетов',
                'ordering': ['-created_at', '-pk'],
            },
        ),
        migrations.CreateModel(
            name='CustomerConsent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('account', 'Обработка персональных данных для личного кабинета')], max_length=32, verbose_name='Цель')),
                ('document_version', models.CharField(max_length=64, verbose_name='Версия текста')),
                ('action', models.CharField(max_length=64, verbose_name='Действие')),
                ('accepted_at', models.DateTimeField(auto_now_add=True, verbose_name='Дано')),
                ('withdrawn_at', models.DateTimeField(blank=True, null=True, verbose_name='Отозвано')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer_accounts.customeraccount')),
            ],
            options={
                'verbose_name': 'Согласие клиента',
                'verbose_name_plural': 'Согласия клиентов',
            },
        ),
        migrations.CreateModel(
            name='CustomerSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('revoked_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer_accounts.customeraccount')),
            ],
            options={
                'verbose_name': 'Сессия кабинета',
                'verbose_name_plural': 'Сессии кабинетов',
            },
        ),
        migrations.CreateModel(
            name='CustomerAccountCustomerLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('linked_at', models.DateTimeField(auto_now_add=True)),
                ('unlinked_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer_accounts.customeraccount')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='customers.customer')),
                ('linked_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('unlinked_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name': 'Связь кабинета с карточкой клиента',
                'verbose_name_plural': 'Связи кабинетов с карточками клиентов',
                'constraints': [models.UniqueConstraint(condition=models.Q(('unlinked_at__isnull', True)), fields=('account',), name='customer_link_one_active_per_account'), models.UniqueConstraint(condition=models.Q(('unlinked_at__isnull', True)), fields=('customer',), name='customer_link_one_active_per_customer')],
            },
        ),
        migrations.CreateModel(
            name='CustomerIdentity',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('provider', models.CharField(choices=[('max', 'MAX'), ('telegram', 'Telegram')], max_length=16, verbose_name='Мессенджер')),
                ('provider_user_id', models.BigIntegerField(verbose_name='ID в мессенджере')),
                ('display_name', models.CharField(blank=True, max_length=160, verbose_name='Имя (снимок)')),
                ('verified_at', models.DateTimeField(verbose_name='Подтверждён')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('account', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='identities', to='customer_accounts.customeraccount')),
            ],
            options={
                'verbose_name': 'Мессенджер кабинета',
                'verbose_name_plural': 'Мессенджеры кабинетов',
                'constraints': [models.UniqueConstraint(fields=('provider', 'provider_user_id'), name='customer_identity_unique'), models.UniqueConstraint(fields=('account', 'provider'), name='customer_identity_one_per_provider'), models.CheckConstraint(condition=models.Q(('provider_user_id__gt', 0)), name='customer_identity_positive_id')],
            },
        ),
        migrations.CreateModel(
            name='CustomerLoginAttempt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purpose', models.CharField(choices=[('login', 'Вход'), ('link', 'Подключение мессенджера')], max_length=8, verbose_name='Назначение')),
                ('provider', models.CharField(choices=[('max', 'MAX'), ('telegram', 'Telegram')], max_length=16, verbose_name='Мессенджер')),
                ('status', models.CharField(choices=[('pending', 'Ожидает мессенджер'), ('code_sent', 'Код отправлен'), ('completed', 'Завершена'), ('failed', 'Отклонена')], default='pending', max_length=16, verbose_name='Состояние')),
                ('token_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('browser_hash', models.CharField(editable=False, max_length=64, unique=True)),
                ('provider_user_id', models.BigIntegerField(blank=True, null=True)),
                ('provider_chat_id', models.BigIntegerField(blank=True, null=True)),
                ('display_name', models.CharField(blank=True, max_length=160)),
                ('code_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('code_tries', models.PositiveSmallIntegerField(default=0)),
                ('codes_sent', models.PositiveSmallIntegerField(default=0)),
                ('failure', models.CharField(blank=True, max_length=32)),
                ('client_hash', models.CharField(blank=True, editable=False, max_length=64)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('expires_at', models.DateTimeField()),
                ('verified_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('account', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='+', to='customer_accounts.customeraccount')),
            ],
            options={
                'verbose_name': 'Попытка входа',
                'verbose_name_plural': 'Попытки входа',
                'indexes': [models.Index(fields=['client_hash', 'created_at'], name='customer_attempt_rate_idx')],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('purpose', 'link'), _negated=True), ('account__isnull', False), _connector='OR'), name='customer_attempt_link_has_account')],
            },
        ),
    ]
