# Generated by Django 5.2.15 on 2026-06-26 06:17

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_parttype_partnumber_partbarcode_partcompatibility'),
        ('inventory', '0007_alter_stockmovement_movement_type'),
        ('procurement', '0002_landed_cost'),
        ('repairs', '0002_seed_repair_sequence'),
        ('sales', '0004_seed_sale_sequence'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StockReturn',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Проведён')], default='draft', max_length=20, verbose_name='Статус')),
                ('source_type', models.CharField(choices=[('sale', 'Продажа'), ('repair_order', 'Ремонтный заказ')], max_length=20, verbose_name='Тип источника')),
                ('source_id', models.PositiveIntegerField(verbose_name='ID источника')),
                ('reason', models.CharField(blank=True, max_length=255, verbose_name='Причина возврата')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Себестоимость возвращённого (₽)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Проведён (когда)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Возврат на склад',
                'verbose_name_plural': 'Возвраты на склад',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='StockReturnLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('restock_status', models.CharField(choices=[('available', 'Доступен'), ('quarantine', 'Карантин')], default='quarantine', max_length=20, verbose_name='Состояние возврата')),
                ('unit_cost_rub', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Себестоимость за ед. (₽)')),
                ('total_cost_rub', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Себестоимость строки (₽)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='procurement.batch', verbose_name='Партия')),
                ('batch_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='procurement.batchline', verbose_name='Строка партии')),
                ('part_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='inventory.partitem', verbose_name='Экземпляр')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.parttype', verbose_name='Деталь')),
                ('returned_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_target_lines', to='inventory.stocklot', verbose_name='Лот зачисления')),
                ('source_repair_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='repairs.repairissueline', verbose_name='Строка выдачи в ремонт')),
                ('source_sale_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_lines', to='sales.saleline', verbose_name='Строка продажи')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='return_source_lines', to='inventory.stocklot', verbose_name='Лот-источник')),
                ('stock_return', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='returns.stockreturn', verbose_name='Возврат')),
                ('to_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.storagelocation', verbose_name='Ячейка возврата')),
            ],
            options={
                'verbose_name': 'Позиция возврата',
                'verbose_name_plural': 'Позиции возврата',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('source_repair_line__isnull', True), ('source_sale_line__isnull', False)), models.Q(('source_repair_line__isnull', False), ('source_sale_line__isnull', True)), _connector='OR'), name='returnline_source_xor'), models.CheckConstraint(condition=models.Q(models.Q(('part_item__isnull', False), ('stock_lot__isnull', True)), models.Q(('part_item__isnull', True), ('stock_lot__isnull', False)), _connector='OR'), name='returnline_item_xor_lot'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='returnline_qty_positive')],
            },
        ),
    ]
