# Generated by Django 5.2.15 on 2026-07-13 09:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0002_seed_return_sequence'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreturn',
            name='completed_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто провёл'),
        ),
        migrations.AlterField(
            model_name='stockreturnline',
            name='restock_status',
            field=models.CharField(choices=[('available', 'Доступен'), ('quarantine', 'Карантин')], default='available', max_length=20, verbose_name='Состояние возврата'),
        ),
    ]
