# Generated by Django 5.2.15 on 2026-07-15 21:54

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('returns', '0003_stockreturn_completed_by_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='stockreturn',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='stockreturn',
            name='canceled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменён (когда)'),
        ),
        migrations.AddField(
            model_name='stockreturn',
            name='canceled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто отменил'),
        ),
        migrations.AlterField(
            model_name='stockreturn',
            name='status',
            field=models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Проведён'), ('canceled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус'),
        ),
    ]
