# Generated by Django 5.2.15 on 2026-07-08 12:06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_parttypeimage'),
        ('repairs', '0002_seed_repair_sequence'),
        ('sales', '0004_seed_sale_sequence'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartCustomsInfo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('customs_name_ru', models.CharField(blank=True, max_length=255, verbose_name='Таможенное название (RU)')),
                ('customs_name_source', models.CharField(choices=[('manual', 'Введено вручную'), ('auto_translation', 'Автоперевод')], default='auto_translation', max_length=20, verbose_name='Источник названия')),
                ('manufacturer', models.CharField(default='BRP', max_length=80, verbose_name='Производитель')),
                ('country_of_origin', models.CharField(default='КАНАДА', max_length=80, verbose_name='Страна производства')),
                ('gross_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Вес брутто, кг/шт')),
                ('net_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True, verbose_name='Вес нетто, кг/шт')),
                ('weight_source_url', models.URLField(blank=True, verbose_name='Источник веса (URL)')),
                ('weight_source_note', models.CharField(blank=True, max_length=255, verbose_name='Источник веса (примечание)')),
                ('weight_verified', models.BooleanField(default=False, verbose_name='Вес проверен')),
                ('application_area', models.CharField(default='МОТО ЗАПЧАСТИ', max_length=120, verbose_name='Область применения')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part_type', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='customs_info', to='catalog.parttype', verbose_name='Деталь')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Таможенные данные детали',
                'verbose_name_plural': 'Таможенные данные деталей',
            },
        ),
        migrations.CreateModel(
            name='WarehouseAction',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('action_type', models.CharField(choices=[('sale', 'Продажа'), ('reserve', 'Резерв'), ('repair', 'Ремонт')], max_length=10, verbose_name='Тип')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('unit_price_rub', models.DecimalField(decimal_places=2, default=0, max_digits=12, verbose_name='Цена клиента за ед. (₽)')),
                ('total_price_rub', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Сумма (₽)')),
                ('customer_comment', models.CharField(max_length=255, verbose_name='Клиент / комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Проведено')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто провёл')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_actions', to='warehouse.storagelocation', verbose_name='Ячейка списания')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='warehouse_actions', to='catalog.parttype', verbose_name='Деталь')),
                ('repair_order', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanner_actions', to='repairs.repairorder', verbose_name='Ремонтный заказ')),
                ('reservation', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanner_actions', to='sales.reservation', verbose_name='Резерв')),
                ('sale', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scanner_actions', to='sales.sale', verbose_name='Продажа')),
            ],
            options={
                'verbose_name': 'Действие со склада',
                'verbose_name_plural': 'Действия со склада',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='warehouseaction_qty_positive')],
            },
        ),
    ]
