# Generated by Django 5.2.15 on 2026-07-09 09:24

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseaction',
            name='cancel_reason',
            field=models.CharField(blank=True, max_length=255, verbose_name='Причина отмены'),
        ),
        migrations.AddField(
            model_name='warehouseaction',
            name='cancelled_at',
            field=models.DateTimeField(blank=True, null=True, verbose_name='Отменено (когда)'),
        ),
        migrations.AddField(
            model_name='warehouseaction',
            name='cancelled_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто отменил'),
        ),
        migrations.AddField(
            model_name='warehouseaction',
            name='location_code',
            field=models.CharField(blank=True, max_length=80, verbose_name='Ячейка (снимок)'),
        ),
        migrations.AddField(
            model_name='warehouseaction',
            name='part_name',
            field=models.CharField(blank=True, max_length=255, verbose_name='Название (снимок)'),
        ),
        migrations.AddField(
            model_name='warehouseaction',
            name='part_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер детали (снимок)'),
        ),
        migrations.AddField(
            model_name='warehouseaction',
            name='price_source_number',
            field=models.CharField(blank=True, max_length=100, verbose_name='Номер источника цены'),
        ),
        migrations.AddField(
            model_name='warehouseaction',
            name='status',
            field=models.CharField(choices=[('active', 'Проведено'), ('cancelled', 'Отменено')], db_index=True, default='active', max_length=10, verbose_name='Статус'),
        ),
    ]
