# Generated by Django 5.2.15 on 2026-07-09 11:43

from django.db import migrations, models


def backfill_manufacturer(apps, schema_editor):
    WarehouseAction = apps.get_model("actions", "WarehouseAction")
    for action in WarehouseAction.objects.select_related("part_type__manufacturer"):
        if action.manufacturer_name:
            continue
        manufacturer = action.part_type.manufacturer
        if manufacturer is None:
            continue
        action.manufacturer_name = manufacturer.name
        action.save(update_fields=["manufacturer_name"])


def noop(apps, schema_editor):
    pass


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0003_backfill_action_identity_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseaction',
            name='manufacturer_name',
            field=models.CharField(blank=True, max_length=80, verbose_name='Производитель (снимок)'),
        ),
        migrations.RunPython(backfill_manufacturer, noop),
    ]
