# Generated by Django 5.2.15 on 2026-07-10 18:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0004_warehouseaction_manufacturer_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partcustomsinfo',
            name='application_area',
            field=models.CharField(blank=True, choices=[('СНЕГОХОД', 'Снегоход'), ('КВАДРОЦИКЛ', 'Квадроцикл'), ('ГИДРОЦИКЛ', 'Гидроцикл'), ('КАТЕР / ЛОДКА', 'Катер / лодка'), ('АВТОМОБИЛЬ', 'Автомобиль'), ('УНИВЕРСАЛЬНЫЕ ЗАПЧАСТИ', 'Универсальные запчасти')], default='', max_length=120, verbose_name='Область применения'),
        ),
    ]
