# Generated by Django 5.2.15 on 2026-07-15 21:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0007_warehouseaction_repair_issue_line_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='warehouseaction',
            name='request_token',
            field=models.CharField(blank=True, editable=False, max_length=64, null=True, unique=True, verbose_name='Токен запроса'),
        ),
    ]
