# Generated by Django 5.2.15 on 2026-08-26 06:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0008_warehouseaction_request_token'),
        ('catalog', '0006_alter_partnumber_kind'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partcustomsinfo',
            name='customs_name_en',
            field=models.CharField(blank=True, max_length=255, verbose_name='Таможенное название (EN)'),
        ),
        migrations.AddField(
            model_name='partcustomsinfo',
            name='customs_unit_price_usd',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Таможенная цена за единицу, USD'),
        ),
        migrations.AddField(
            model_name='partcustomsinfo',
            name='source_reference',
            field=models.CharField(blank=True, max_length=255, verbose_name='Источник / документ'),
        ),
        migrations.AlterField(
            model_name='partcustomsinfo',
            name='country_of_origin',
            field=models.CharField(blank=True, max_length=80, verbose_name='Страна производства'),
        ),
        migrations.CreateModel(
            name='PartCustomsDataVersion',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('version', models.PositiveIntegerField(verbose_name='Версия')),
                ('effective_from', models.DateTimeField(db_index=True, verbose_name='Действует с')),
                ('customs_name_ru', models.CharField(blank=True, max_length=255, verbose_name='Таможенное название (RU)')),
                ('customs_name_en', models.CharField(blank=True, max_length=255, verbose_name='Таможенное название (EN)')),
                ('manufacturer', models.CharField(blank=True, max_length=80, verbose_name='Производитель')),
                ('country_of_origin', models.CharField(blank=True, max_length=80, verbose_name='Страна производства')),
                ('gross_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('net_weight_kg', models.DecimalField(blank=True, decimal_places=3, max_digits=8, null=True)),
                ('customs_unit_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True)),
                ('application_area', models.CharField(blank=True, max_length=120)),
                ('source_reference', models.CharField(blank=True, max_length=255)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто сохранил')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='customs_data_versions', to='catalog.parttype', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Версия таможенных данных',
                'verbose_name_plural': 'Версии таможенных данных',
                'ordering': ['part_type_id', 'version'],
                'constraints': [models.UniqueConstraint(fields=('part_type', 'version'), name='customs_version_per_part')],
            },
        ),
    ]
