# Generated by Django 5.2.17 on 2026-09-07 15:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0011_customs_name_ru_confirmation'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partcustomsinfo',
            name='application_area',
            field=models.CharField(blank=True, choices=[('СНЕГОХОД', 'Снегоход'), ('КВАДРОЦИКЛ', 'Квадроцикл'), ('ГИДРОЦИКЛ', 'Гидроцикл'), ('ЛОДОЧНЫЙ МОТОР', 'Лодочный мотор'), ('КАТЕР', 'Катер'), ('КАТЕР / ЛОДКА', 'Катер / лодка'), ('АВТОМОБИЛЬ', 'Автомобиль'), ('УНИВЕРСАЛЬНЫЕ ЗАПЧАСТИ', 'Универсальные запчасти')], default='', max_length=120, verbose_name='Область применения'),
        ),
    ]
