# Generated by Django 5.2.17 on 2026-09-19 09:46

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('actions', '0015_customs_search_name_ru'),
        ('catalog', '0013_parttype_search_name_compact_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='partcustomsinfo',
            name='search_name_ru_compact',
            field=models.CharField(blank=True, editable=False, max_length=255, verbose_name='Русское название для поиска без разделителей'),
        ),
        migrations.AddIndex(
            model_name='partcustomsinfo',
            index=models.Index(fields=['search_name_ru_compact'], name='customs_name_ru_compact_idx'),
        ),
    ]
