# Generated by Django 5.2.17 on 2026-09-24 03:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("actions", "0018_compact_name_ru_pattern_index"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partcustomsinfo",
            name="manufacturer",
            field=models.CharField(
                blank=True, default="", max_length=80, verbose_name="Производитель"
            ),
        ),
    ]
