# Generated by Django 5.2.15 on 2026-06-25 04:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_parttype_partnumber_partbarcode_partcompatibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UnresolvedScan',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(max_length=255, verbose_name='Код')),
                ('normalized_value', models.CharField(blank=True, db_index=True, max_length=255)),
                ('context', models.CharField(blank=True, max_length=60, verbose_name='Контекст')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('resolved', models.BooleanField(default=False, verbose_name='Разобран')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('resolved_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.parttype', verbose_name='Привязан к детали')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто сканировал')),
            ],
            options={
                'verbose_name': 'Нераспознанный скан',
                'verbose_name_plural': 'Нераспознанные сканы',
                'ordering': ['-created_at'],
            },
        ),
    ]
