# Generated by Django 5.2.15 on 2026-07-06 16:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('brp', '0001_initial'),
        ('catalog', '0004_parttypeimage'),
        ('receipts', '0002_seed_receipt_sequence'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCountingSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('full_address', models.CharField(max_length=80, verbose_name='Полный адрес')),
                ('title', models.CharField(blank=True, max_length=120, verbose_name='Название')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('converted', 'Черновик документа создан'), ('posted', 'Проведено'), ('cancelled', 'Отменено')], default='draft', max_length=20, verbose_name='Статус')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('posted_at', models.DateTimeField(blank=True, null=True, verbose_name='Проведено (когда)')),
                ('converted_receipt', models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counting_session', to='receipts.receipt', verbose_name='Документ инвентаризации')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто начал')),
                ('storage_location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='counting_sessions', to='warehouse.storagelocation', verbose_name='Место хранения')),
            ],
            options={
                'verbose_name': 'Пересчёт ячейки',
                'verbose_name_plural': 'Пересчёты ячеек',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountingLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('scanned_value', models.CharField(max_length=120, verbose_name='Номер')),
                ('normalized_value', models.CharField(db_index=True, max_length=120)),
                ('display_name', models.CharField(blank=True, max_length=255, verbose_name='Название')),
                ('source', models.CharField(choices=[('warehouse', 'На складе'), ('brp_catalog', 'BRP-каталог'), ('unknown', 'Неизвестно'), ('manual', 'Вручную')], default='unknown', max_length=20, verbose_name='Источник')),
                ('quantity_counted', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Количество')),
                ('scan_count', models.PositiveIntegerField(default=0, verbose_name='Сканов')),
                ('final_customer_price_rub', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='Цена клиента (₽)')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('last_scanned_at', models.DateTimeField(blank=True, null=True)),
                ('brp_catalog_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='brp.brpcatalogpart', verbose_name='Позиция BRP')),
                ('warehouse_part', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='catalog.parttype', verbose_name='Карточка склада')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='counting.inventorycountingsession')),
            ],
            options={
                'verbose_name': 'Строка пересчёта',
                'verbose_name_plural': 'Строки пересчёта',
                'ordering': ['-last_scanned_at', 'id'],
            },
        ),
        migrations.CreateModel(
            name='InventoryScanEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('raw_value', models.CharField(max_length=120, verbose_name='Отсканировано')),
                ('normalized_value', models.CharField(db_index=True, max_length=120)),
                ('is_reverted', models.BooleanField(default=False, verbose_name='Отменён')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('matched_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='scan_events', to='counting.inventorycountingline')),
                ('session', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='scans', to='counting.inventorycountingsession')),
            ],
            options={
                'verbose_name': 'Скан-событие',
                'verbose_name_plural': 'Скан-события',
                'ordering': ['-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='inventorycountingline',
            constraint=models.UniqueConstraint(fields=('session', 'normalized_value'), name='uniq_countingline_session_norm'),
        ),
    ]
