# Generated by Django 5.2.15 on 2026-07-09 08:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0001_initial'),
        ('receipts', '0002_seed_receipt_sequence'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycountingsession',
            name='inventory_number',
            field=models.CharField(blank=True, db_index=True, default='', editable=False, max_length=20, verbose_name='Номер инвентаризации'),
        ),
        migrations.AlterField(
            model_name='inventorycountingsession',
            name='converted_receipt',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='counting_session', to='receipts.receipt', verbose_name='Технический документ проведения'),
        ),
    ]
