# Generated by Django 5.2.15 on 2026-07-09 11:43

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0002_inventorycountingsession_inventory_number_and_more'),
        ('polaris', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='inventorycountingline',
            name='polaris_catalog_part',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to='polaris.polariscatalogpart', verbose_name='Позиция Polaris'),
        ),
        migrations.AlterField(
            model_name='inventorycountingline',
            name='source',
            field=models.CharField(choices=[('warehouse', 'На складе'), ('brp_catalog', 'BRP-каталог'), ('polaris_catalog', 'Polaris-каталог'), ('unknown', 'Неизвестно'), ('manual', 'Вручную')], default='unknown', max_length=20, verbose_name='Источник'),
        ),
    ]
