# Generated by Django 5.2.15 on 2026-08-27 20:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('counting', '0004_inventoryscanevent_request_token'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inventorycountingline',
            name='source',
            field=models.CharField(choices=[('warehouse', 'На складе'), ('aftermarket_catalog', 'Каталог аналогов'), ('brp_catalog', 'BRP-каталог'), ('polaris_catalog', 'Polaris-каталог'), ('unknown', 'Неизвестно'), ('manual', 'Вручную')], default='unknown', max_length=20, verbose_name='Источник'),
        ),
    ]
