# Generated by Django 5.2.15 on 2026-06-24 09:48

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='Название')),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='Код')),
                ('barcode', models.CharField(blank=True, max_length=80, unique=True, verbose_name='Штрихкод')),
                ('level', models.CharField(choices=[('warehouse', 'Склад'), ('zone', 'Зона'), ('rack', 'Стеллаж'), ('section', 'Секция'), ('shelf', 'Полка'), ('cell', 'Ячейка')], default='cell', max_length=20, verbose_name='Уровень')),
                ('purpose', models.CharField(choices=[('normal', 'Обычное'), ('receiving', 'Приёмка'), ('quarantine', 'Карантин'), ('writeoff', 'Списание')], default='normal', max_length=20, verbose_name='Назначение')),
                ('storage_allowed', models.BooleanField(default=True, verbose_name='Можно хранить остаток')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('capacity', models.PositiveIntegerField(blank=True, null=True, verbose_name='Вместимость')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('parent', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='children', to='warehouse.storagelocation', verbose_name='Родитель')),
            ],
            options={
                'verbose_name': 'Место хранения',
                'verbose_name_plural': 'Места хранения',
                'ordering': ['sort_order', 'code'],
            },
        ),
    ]
