# Generated by Django 5.2.15 on 2026-07-10 05:45

from decimal import Decimal
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ValuationSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('purchase_usd_rate', models.DecimalField(decimal_places=4, default=Decimal('105'), max_digits=10, verbose_name='Курс для оценки закупочной стоимости (₽ за $)')),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Настройки оценки склада',
                'verbose_name_plural': 'Настройки оценки склада',
            },
        ),
    ]
