# Generated by Django 5.2.15 on 2026-07-14 09:38

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0003_unified_current_usd_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='StorageLocationRenameHistory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('old_code', models.CharField(max_length=60, verbose_name='Старый код')),
                ('new_code', models.CharField(max_length=60, verbose_name='Новый код')),
                ('renamed_at', models.DateTimeField(auto_now_add=True, db_index=True, verbose_name='Переименовано')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='rename_history', to='warehouse.storagelocation', verbose_name='Ячейка')),
                ('renamed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто переименовал')),
            ],
            options={
                'verbose_name': 'История переименования ячейки',
                'verbose_name_plural': 'История переименований ячеек',
                'ordering': ['-renamed_at', '-pk'],
            },
        ),
    ]
