# Generated by Django 5.2.15 on 2026-08-11 19:51

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0004_storagelocationrenamehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocationrenamehistory',
            name='operation_key',
            field=models.CharField(blank=True, db_index=True, max_length=64, verbose_name='Ключ групповой операции'),
        ),
        migrations.AddField(
            model_name='storagelocationrenamehistory',
            name='reason',
            field=models.CharField(choices=[('manual', 'Ручное переименование'), ('drawer', 'Переименование ящика'), ('address_v2', 'Миграция адреса V2')], default='manual', max_length=20, verbose_name='Причина'),
        ),
        migrations.AlterField(
            model_name='storagelocation',
            name='level',
            field=models.CharField(choices=[('warehouse', 'Склад'), ('zone', 'Зона (legacy)'), ('rack', 'Стеллаж'), ('drawer', 'Ящик'), ('section', 'Секция (legacy)'), ('shelf', 'Полка (legacy)'), ('cell', 'Ячейка')], default='cell', max_length=20, verbose_name='Тип места'),
        ),
        migrations.CreateModel(
            name='StorageLocationAlias',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('code', models.CharField(max_length=60, unique=True, verbose_name='Исторический код')),
                ('barcode', models.CharField(blank=True, max_length=80, null=True, unique=True, verbose_name='Исторический штрихкод')),
                ('kind', models.CharField(choices=[('rename', 'Переименование'), ('drawer', 'Переименование ящика'), ('address_v2', 'Миграция адреса V2')], default='rename', max_length=20, verbose_name='Источник')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='aliases', to='warehouse.storagelocation', verbose_name='Текущее место')),
            ],
            options={
                'verbose_name': 'Исторический адрес места',
                'verbose_name_plural': 'Исторические адреса мест',
                'ordering': ['-created_at', '-pk'],
            },
        ),
    ]
