# Generated by Django 5.2.17 on 2026-08-27 14:30

import django.db.models.functions.text
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('warehouse', '0005_storagelocationrenamehistory_operation_key_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='storagelocationalias',
            name='is_active',
            field=models.BooleanField(db_index=True, default=True, help_text='Выключается навсегда, когда historical code повторно становится текущим кодом другой ячейки.', verbose_name='Участвует в operational lookup'),
        ),
        migrations.AlterField(
            model_name='storagelocationalias',
            name='barcode',
            field=models.CharField(blank=True, max_length=80, null=True, verbose_name='Исторический штрихкод'),
        ),
        migrations.AlterField(
            model_name='storagelocationalias',
            name='code',
            field=models.CharField(max_length=60, verbose_name='Исторический код'),
        ),
        migrations.AddConstraint(
            model_name='storagelocationalias',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('code'), condition=models.Q(('is_active', True)), name='warehouse_active_alias_code_ci_uniq'),
        ),
        migrations.AddConstraint(
            model_name='storagelocationalias',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Upper('barcode'), condition=models.Q(('barcode__isnull', False), ('is_active', True)), name='warehouse_active_alias_barcode_ci_uniq'),
        ),
    ]
