# Generated by Django 5.2.15 on 2026-07-09 11:43

import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0004_parttypeimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PolarisCatalogPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=40, unique=True, verbose_name='Номер Polaris')),
                ('part_number_norm', models.CharField(db_index=True, editable=False, max_length=40)),
                ('part_name', models.CharField(blank=True, max_length=255, verbose_name='Название Polaris')),
                ('superseded_number', models.CharField(blank=True, max_length=40, verbose_name='Superseded number')),
                ('superseded_number_norm', models.CharField(db_index=True, editable=False, max_length=40)),
                ('wholesale_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Оптовая Polaris (USD)')),
                ('retail_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Розница Polaris (USD)')),
                ('uom', models.CharField(blank=True, max_length=40, verbose_name='UOM')),
                ('source_file', models.CharField(blank=True, max_length=255, verbose_name='Файл импорта')),
                ('source_row', models.PositiveIntegerField(blank=True, null=True, verbose_name='Строка в файле')),
                ('import_batch', models.CharField(blank=True, max_length=40, verbose_name='Партия импорта')),
                ('imported_at', models.DateTimeField(auto_now_add=True, verbose_name='Импортировано')),
                ('updated_at', models.DateTimeField(auto_now=True, verbose_name='Обновлено')),
            ],
            options={
                'verbose_name': 'Позиция Polaris-каталога',
                'verbose_name_plural': 'Позиции Polaris-каталога',
                'ordering': ['part_number'],
                'indexes': [models.Index(fields=['part_name'], name='polaris_part_name_idx')],
            },
        ),
        migrations.CreateModel(
            name='PolarisPartLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polaris_retail_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Розница Polaris (USD)')),
                ('polaris_wholesale_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Оптовая Polaris (USD)')),
                ('usd_rate_used', models.DecimalField(decimal_places=4, max_digits=10, verbose_name='Курс на момент расчёта')),
                ('markup_percent_used', models.DecimalField(decimal_places=2, max_digits=6, verbose_name='Наценка на момент расчёта, %')),
                ('calculated_customer_price_rub', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='Рассчитанная цена клиента (₽)')),
                ('manual_customer_price_rub', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='Цена клиента вручную (₽)')),
                ('final_customer_price_rub', models.DecimalField(blank=True, decimal_places=6, max_digits=16, null=True, verbose_name='Итоговая цена клиента (₽)')),
                ('price_source', models.CharField(choices=[('calculated', 'Рассчитана по формуле'), ('manual', 'Указана вручную')], default='calculated', max_length=20, verbose_name='Источник цены')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто добавил')),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='polaris_link', to='catalog.parttype', verbose_name='Карточка склада')),
                ('polaris_part', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='links', to='polaris.polariscatalogpart', verbose_name='Позиция Polaris')),
            ],
            options={
                'verbose_name': 'Связь склада с Polaris-каталогом',
                'verbose_name_plural': 'Связи склада с Polaris-каталогом',
            },
        ),
        migrations.CreateModel(
            name='PolarisPricingSettings',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('polaris_usd_rate', models.DecimalField(decimal_places=4, default=Decimal('105'), max_digits=10, verbose_name='Курс расчёта (₽ за $)')),
                ('polaris_markup_percent', models.DecimalField(decimal_places=2, default=Decimal('40'), max_digits=6, verbose_name='Наценка, %')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Настройки цен Polaris',
                'verbose_name_plural': 'Настройки цен Polaris',
            },
        ),
    ]
