# Generated by Django 5.2.15 on 2026-06-26 16:41

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_parttype_partnumber_partbarcode_partcompatibility'),
        ('inventory', '0008_alter_stockmovement_movement_type'),
        ('procurement', '0002_landed_cost'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='WriteOffDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Проведён'), ('canceled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('reason', models.CharField(choices=[('damaged', 'Повреждение'), ('lost', 'Потеря'), ('defect', 'Брак'), ('disposal', 'Утилизация'), ('obsolete', 'Неликвид'), ('other', 'Прочее')], max_length=20, verbose_name='Причина')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('cost_total', models.DecimalField(decimal_places=2, default=0, max_digits=14, verbose_name='Себестоимость списанного (₽)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Проведён (когда)')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменён (когда)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Документ списания',
                'verbose_name_plural': 'Документы списания',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='WriteOffLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('unit_cost_rub', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Себестоимость за ед. (₽)')),
                ('total_cost_rub', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Себестоимость строки (₽)')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('written_off_at', models.DateTimeField(blank=True, null=True, verbose_name='Списано (когда)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='procurement.batch', verbose_name='Партия')),
                ('batch_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='procurement.batchline', verbose_name='Строка партии')),
                ('part_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_off_lines', to='inventory.partitem', verbose_name='Экземпляр')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.parttype', verbose_name='Деталь')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='write_off_lines', to='inventory.stocklot', verbose_name='Лот')),
                ('write_off', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='writeoffs.writeoffdocument', verbose_name='Документ списания')),
            ],
            options={
                'verbose_name': 'Позиция списания',
                'verbose_name_plural': 'Позиции списания',
                'ordering': ['id'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('part_item__isnull', False), ('stock_lot__isnull', True)), models.Q(('part_item__isnull', True), ('stock_lot__isnull', False)), _connector='OR'), name='writeoffline_item_xor_lot'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='writeoffline_qty_positive')],
            },
        ),
    ]
