# Generated by Django 5.2.17 on 2026-10-04 08:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("writeoffs", "0004_writeoffline_source_snapshot"),
    ]

    operations = [
        migrations.AddField(
            model_name="writeoffdocument",
            name="request_token",
            field=models.CharField(
                blank=True,
                editable=False,
                max_length=64,
                null=True,
                unique=True,
                verbose_name="Токен запроса",
            ),
        ),
    ]
