# Generated by Django 5.2.15 on 2026-06-24 15:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_parttype_partnumber_partbarcode_partcompatibility'),
        ('procurement', '0002_landed_cost'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='NumberSequence',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('key', models.CharField(max_length=50, unique=True, verbose_name='Ключ')),
                ('prefix', models.CharField(max_length=10, verbose_name='Префикс')),
                ('last_value', models.PositiveIntegerField(default=0, verbose_name='Последнее значение')),
            ],
            options={
                'verbose_name': 'Счётчик номеров',
                'verbose_name_plural': 'Счётчики номеров',
            },
        ),
        migrations.CreateModel(
            name='PartItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('internal_number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Внутренний номер')),
                ('internal_barcode', models.CharField(editable=False, max_length=40, unique=True, verbose_name='Внутренний штрихкод')),
                ('serial_number', models.CharField(blank=True, max_length=100, verbose_name='Серийный номер')),
                ('landed_cost_rub', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Себестоимость (₽)')),
                ('status', models.CharField(choices=[('receiving', 'На приёмке'), ('available', 'Доступен'), ('reserved', 'Зарезервирован'), ('sold', 'Продан'), ('installed', 'Установлен'), ('repair', 'В ремонте'), ('written_off', 'Списан'), ('returned', 'Возвращён'), ('quarantine', 'Карантин')], default='receiving', max_length=20, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='procurement.batch', verbose_name='Партия')),
                ('batch_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='procurement.batchline', verbose_name='Строка партии')),
                ('current_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='items', to='warehouse.storagelocation', verbose_name='Место')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='items', to='catalog.parttype', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Экземпляр детали',
                'verbose_name_plural': 'Экземпляры деталей',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(condition=models.Q(('serial_number', ''), _negated=True), fields=('part_type', 'serial_number'), name='uniq_partitem_serial_per_parttype')],
            },
        ),
    ]
