# Generated by Django 5.2.15 on 2026-06-24 15:39

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_parttype_partnumber_partbarcode_partcompatibility'),
        ('inventory', '0002_seed_number_sequence'),
        ('procurement', '0002_landed_cost'),
        ('warehouse', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLot',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('initial_quantity', models.DecimalField(decimal_places=3, editable=False, max_digits=12, verbose_name='Исходное количество')),
                ('landed_unit_cost_rub', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Себестоимость за ед. (₽)')),
                ('status', models.CharField(choices=[('receiving', 'На приёмке'), ('available', 'Доступен'), ('quarantine', 'Карантин'), ('written_off', 'Списан')], default='receiving', max_length=20, verbose_name='Статус')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='procurement.batch', verbose_name='Партия')),
                ('batch_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='lots', to='procurement.batchline', verbose_name='Строка партии')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='warehouse.storagelocation', verbose_name='Место')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_lots', to='catalog.parttype', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Складской лот',
                'verbose_name_plural': 'Складские лоты',
                'ordering': ['-created_at'],
                'constraints': [models.UniqueConstraint(fields=('batch_line', 'location'), name='uniq_stocklot_line_location'), models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='stocklot_quantity_non_negative'), models.CheckConstraint(condition=models.Q(('initial_quantity__gte', 0)), name='stocklot_initial_non_negative')],
            },
        ),
    ]
