# Generated by Django 5.2.15 on 2026-06-24 20:03

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_parttype_partnumber_partbarcode_partcompatibility'),
        ('inventory', '0003_stocklot'),
        ('procurement', '0002_landed_cost'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AlterField(
            model_name='stocklot',
            name='status',
            field=models.CharField(choices=[('receiving', 'На приёмке'), ('available', 'Доступен'), ('quarantine', 'Карантин'), ('written_off', 'Списан'), ('depleted', 'Исчерпан')], default='receiving', max_length=20, verbose_name='Статус'),
        ),
        migrations.CreateModel(
            name='StockBalance',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity_physical', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Физически в ячейке')),
                ('quantity_available', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Доступно')),
                ('quantity_reserved', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Зарезервировано')),
                ('quantity_in_repair', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='В ремонте')),
                ('quantity_quarantine', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='В карантине')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='procurement.batch', verbose_name='Партия')),
                ('batch_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='procurement.batchline', verbose_name='Строка партии')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='warehouse.storagelocation', verbose_name='Место')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='balances', to='catalog.parttype', verbose_name='Деталь')),
            ],
            options={
                'verbose_name': 'Остаток (кэш)',
                'verbose_name_plural': 'Остатки (кэш)',
                'ordering': ['part_type_id', 'location_id'],
                'indexes': [models.Index(fields=['part_type', 'location'], name='stockbalance_part_loc_idx')],
                'constraints': [models.UniqueConstraint(fields=('batch_line', 'location'), name='uniq_stockbalance_line_location')],
            },
        ),
        migrations.CreateModel(
            name='StockMovement',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('movement_type', models.CharField(choices=[('receive_item', 'Приёмка экземпляра'), ('receive_lot', 'Приёмка лота'), ('move_item', 'Перемещение экземпляра'), ('move_lot', 'Перемещение лота'), ('adjust_in', 'Корректировка +'), ('adjust_out', 'Корректировка −')], max_length=20, verbose_name='Тип движения')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('unit_cost_rub', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Себестоимость за ед. (₽)')),
                ('total_cost_rub', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=14, verbose_name='Себестоимость движения (₽)')),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('document_type', models.CharField(blank=True, max_length=40, verbose_name='Тип документа')),
                ('document_id', models.PositiveIntegerField(blank=True, null=True, verbose_name='ID документа')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('batch', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='procurement.batch', verbose_name='Партия')),
                ('batch_line', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='procurement.batchline', verbose_name='Строка партии')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто провёл')),
                ('from_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_out', to='warehouse.storagelocation', verbose_name='Откуда')),
                ('part_item', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.partitem', verbose_name='Экземпляр')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='catalog.parttype', verbose_name='Деталь')),
                ('stock_lot', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements', to='inventory.stocklot', verbose_name='Лот')),
                ('to_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='movements_in', to='warehouse.storagelocation', verbose_name='Куда')),
            ],
            options={
                'verbose_name': 'Складское движение',
                'verbose_name_plural': 'Складские движения',
                'ordering': ['-created_at'],
                'constraints': [models.CheckConstraint(condition=models.Q(models.Q(('part_item__isnull', False), ('stock_lot__isnull', True)), models.Q(('part_item__isnull', True), ('stock_lot__isnull', False)), _connector='OR'), name='stockmovement_item_xor_lot'), models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='stockmovement_quantity_positive')],
            },
        ),
    ]
