# Generated by Django 5.2.15 on 2026-06-25 17:51

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0004_alter_stocklot_status_stockbalance_stockmovement'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receive_item', 'Приёмка экземпляра'), ('receive_lot', 'Приёмка лота'), ('move_item', 'Перемещение экземпляра'), ('move_lot', 'Перемещение лота'), ('adjust_in', 'Корректировка +'), ('adjust_out', 'Корректировка −'), ('sale_item', 'Продажа экземпляра'), ('sale_lot', 'Продажа лота')], max_length=20, verbose_name='Тип движения'),
        ),
    ]
