# Generated by Django 5.2.15 on 2026-07-10 08:08

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0009_partitemimage'),
        ('warehouse', '0003_unified_current_usd_rate'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='FoundStockPosting',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('token', models.CharField(max_length=64, unique=True, verbose_name='Одноразовый токен')),
                ('line_count', models.PositiveIntegerField(verbose_name='Позиций')),
                ('quantity', models.PositiveIntegerField(verbose_name='Единиц')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто провёл')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='found_stock_postings', to='warehouse.storagelocation', verbose_name='Ячейка')),
            ],
            options={
                'verbose_name': 'Проведение найденных деталей',
                'verbose_name_plural': 'Проведения найденных деталей',
                'ordering': ['-created_at'],
            },
        ),
    ]
