# Generated by Django 5.2.15 on 2026-07-15

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("inventory", "0010_found_stock_posting"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="StockTransfer",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True, primary_key=True, serialize=False, verbose_name="ID"
                    ),
                ),
                ("token", models.CharField(max_length=64, unique=True, verbose_name="Одноразовый токен")),
                (
                    "stock_state",
                    models.CharField(
                        choices=[
                            ("available", "Доступный остаток"),
                            ("quarantine", "Карантин"),
                            ("serial", "Экземпляр"),
                        ],
                        max_length=20,
                        verbose_name="Состояние",
                    ),
                ),
                ("part_number", models.CharField(max_length=100, verbose_name="Номер детали (снимок)")),
                ("part_name", models.CharField(max_length=255, verbose_name="Название (снимок)")),
                ("manufacturer_name", models.CharField(blank=True, max_length=80, verbose_name="Производитель (снимок)")),
                ("from_location_code", models.CharField(max_length=80, verbose_name="Откуда (снимок)")),
                ("to_location_code", models.CharField(max_length=80, verbose_name="Куда (снимок)")),
                ("quantity", models.DecimalField(decimal_places=3, max_digits=12, verbose_name="Количество")),
                ("created_at", models.DateTimeField(auto_now_add=True, db_index=True, verbose_name="Проведено")),
                (
                    "created_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто провёл",
                    ),
                ),
                (
                    "from_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transfers_out",
                        to="warehouse.storagelocation",
                        verbose_name="Откуда",
                    ),
                ),
                (
                    "part_item",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transfers",
                        to="inventory.partitem",
                        verbose_name="Экземпляр",
                    ),
                ),
                (
                    "part_type",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transfers",
                        to="catalog.parttype",
                        verbose_name="Деталь",
                    ),
                ),
                (
                    "to_location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="stock_transfers_in",
                        to="warehouse.storagelocation",
                        verbose_name="Куда",
                    ),
                ),
            ],
            options={
                "verbose_name": "Перемещение склада",
                "verbose_name_plural": "Перемещения склада",
                "ordering": ["-created_at", "-id"],
            },
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("quantity__gt", 0)),
                name="stocktransfer_quantity_positive",
            ),
        ),
        migrations.AddConstraint(
            model_name="stocktransfer",
            constraint=models.CheckConstraint(
                condition=models.Q(("from_location", models.F("to_location")), _negated=True),
                name="stocktransfer_locations_differ",
            ),
        ),
    ]
