# Generated by Django 5.2.15 on 2026-08-06

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0004_parttypeimage"),
        ("inventory", "0011_stocktransfer"),
        ("warehouse", "0004_storagelocationrenamehistory"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartPreferredLocation",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True, db_index=True)),
                (
                    "location",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferred_for_parts",
                        to="warehouse.storagelocation",
                        verbose_name="Предпочтительная ячейка",
                    ),
                ),
                (
                    "part_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.PROTECT,
                        related_name="preferred_location",
                        to="catalog.parttype",
                        verbose_name="Деталь",
                    ),
                ),
                (
                    "updated_by",
                    models.ForeignKey(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="+",
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="Кто подтвердил",
                    ),
                ),
            ],
            options={
                "verbose_name": "Предпочтительная ячейка детали",
                "verbose_name_plural": "Предпочтительные ячейки деталей",
                "ordering": ["part_type_id"],
            },
        ),
    ]
