# Generated by Django 5.2.15 on 2026-08-07 09:14

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0012_partpreferredlocation'),
        ('warehouse', '0004_storagelocationrenamehistory'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockLocationLock',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(max_length=60, verbose_name='Участок')),
                ('document_id', models.PositiveIntegerField(verbose_name='ID пересчёта')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('released_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='stock_locks', to='warehouse.storagelocation')),
            ],
            options={
                'verbose_name': 'Блокировка ячейки склада',
                'verbose_name_plural': 'Блокировки ячеек склада',
                'constraints': [models.UniqueConstraint(condition=models.Q(('released_at__isnull', True)), fields=('location',), name='uniq_active_stock_location_lock')],
            },
        ),
    ]
