# Generated by Django 5.2.17 on 2026-08-27 20:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_stocklocationlock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='stockmovement',
            name='movement_type',
            field=models.CharField(choices=[('receive_item', 'Приёмка экземпляра'), ('receive_lot', 'Приёмка лота'), ('move_item', 'Перемещение экземпляра'), ('move_lot', 'Перемещение лота'), ('adjust_in', 'Корректировка +'), ('adjust_out', 'Корректировка −'), ('sale_item', 'Продажа экземпляра'), ('sale_lot', 'Продажа лота'), ('issue_item', 'Выдача экземпляра в ремонт'), ('issue_lot', 'Выдача лота в ремонт'), ('return_item', 'Возврат экземпляра на склад'), ('return_lot', 'Возврат лота на склад'), ('write_off_item', 'Списание экземпляра'), ('write_off_lot', 'Списание лота'), ('writeoff_cancel_item', 'Отмена списания экземпляра'), ('writeoff_cancel_lot', 'Отмена списания лота')], max_length=20, verbose_name='Тип движения'),
        ),
    ]
