# Generated by Django 5.2.12 on 2026-09-12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("inventory", "0014_alter_stockmovement_movement_type"),
    ]

    operations = [
        migrations.AddField(
            model_name="partitem",
            name="receipt_customer_price_snapshot_rub",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Снимок канонической цены в момент фактической приёмки.",
                max_digits=12,
                null=True,
                verbose_name="Цена клиента при поступлении (₽)",
            ),
        ),
        migrations.AddField(
            model_name="stocklot",
            name="receipt_customer_price_snapshot_rub",
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                help_text="Снимок канонической цены в момент фактической приёмки.",
                max_digits=12,
                null=True,
                verbose_name="Цена клиента при поступлении (₽)",
            ),
        ),
    ]
