# Generated by Django 5.2.17 on 2026-10-05 16:05

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0015_receipt_customer_price_snapshot'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='origin_transfer',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='target_lots', to='inventory.stocktransfer', verbose_name='Перемещение, создавшее лот'),
        ),
    ]
