# Generated by Django 5.2.17 on 2026-10-05 18:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0016_stocklot_origin_transfer'),
        ('returns', '0004_stockreturn_cancel_reason_stockreturn_canceled_at_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='stocklot',
            name='origin_return_line',
            field=models.ForeignKey(blank=True, editable=False, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='origin_lots', to='returns.stockreturnline', verbose_name='Строка возврата, создавшая лот'),
        ),
    ]
