# Generated by Django 5.2.15 on 2026-08-14 04:16

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='CatalogImportBatch',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('catalog', models.CharField(choices=[('brp', 'BRP')], db_index=True, default='brp', max_length=20, verbose_name='Каталог')),
                ('status', models.CharField(choices=[('uploaded', 'Загружен'), ('checked', 'Проверен'), ('check_failed', 'Проверка не прошла'), ('applied', 'Применён'), ('apply_failed', 'Применение не прошло')], db_index=True, default='uploaded', max_length=20, verbose_name='Статус')),
                ('source_filename', models.CharField(max_length=255, verbose_name='Имя файла')),
                ('source_sha256', models.CharField(db_index=True, max_length=64, verbose_name='SHA-256 файла')),
                ('source_size', models.PositiveBigIntegerField(default=0, verbose_name='Размер файла')),
                ('stored_path', models.CharField(blank=True, max_length=255, verbose_name='Файл в приватном хранилище')),
                ('catalog_fingerprint', models.CharField(blank=True, max_length=64, verbose_name='Слепок каталога')),
                ('summary', models.JSONField(blank=True, default=dict, verbose_name='Сводка проверки')),
                ('apply_summary', models.JSONField(blank=True, default=dict, verbose_name='Сводка применения')),
                ('error_text', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружен')),
                ('checked_at', models.DateTimeField(blank=True, null=True, verbose_name='Проверен (когда)')),
                ('applied_at', models.DateTimeField(blank=True, null=True, verbose_name='Применён (когда)')),
                ('applied_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто применил')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Импорт каталога',
                'verbose_name_plural': 'Импорты каталога',
                'ordering': ['-created_at', '-pk'],
                'indexes': [models.Index(fields=['catalog', '-created_at'], name='catalogimport_recent_idx')],
            },
        ),
    ]
