# Generated by Django 5.2.15 on 2026-08-23 04:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog_import', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimportbatch',
            name='catalog',
            field=models.CharField(choices=[('brp', 'BRP'), ('analogs', 'Аналоги')], db_index=True, default='brp', max_length=20, verbose_name='Каталог'),
        ),
    ]
