# Generated by Django 5.2.15 on 2026-08-25 13:06

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0006_alter_partnumber_kind'),
        ('catalog_import', '0002_alter_catalogimportbatch_catalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimportbatch',
            name='catalog',
            field=models.CharField(choices=[('brp', 'BRP'), ('analogs', 'Аналоги'), ('aftermarket', 'Каталог аналогов / aftermarket')], db_index=True, default='brp', max_length=20, verbose_name='Каталог'),
        ),
        migrations.CreateModel(
            name='AftermarketCatalogPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('dealer_2023', 'Dealer 2023')], max_length=40, verbose_name='Источник каталога')),
                ('manufacturer_number', models.CharField(max_length=100, verbose_name='Номер производителя')),
                ('normalized_manufacturer_number', models.CharField(db_index=True, max_length=100)),
                ('supplier_sku', models.CharField(blank=True, max_length=100, verbose_name='SKU поставщика')),
                ('source_description', models.CharField(max_length=200, verbose_name='Описание поставщика')),
                ('msrp_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='MSRP, USD')),
                ('dealer_cost_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Dlr Cost, USD')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('manufacturer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='catalog.manufacturer')),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='aftermarket_catalog_entry', to='catalog.parttype')),
            ],
            options={
                'verbose_name': 'Позиция aftermarket-каталога',
                'verbose_name_plural': 'Позиции aftermarket-каталога',
                'constraints': [models.UniqueConstraint(fields=('source', 'manufacturer', 'normalized_manufacturer_number'), name='uniq_aftermarket_source_manufacturer_number')],
            },
        ),
    ]
