# Generated by Django 5.2.17 on 2026-09-13 19:31

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_partanalog_public_confirmation'),
        ('catalog_import', '0003_alter_catalogimportbatch_catalog_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='catalogimportbatch',
            name='catalog',
            field=models.CharField(choices=[('brp', 'BRP'), ('arctic_cat', 'Arctic Cat'), ('analogs', 'Аналоги'), ('aftermarket', 'Каталог аналогов / aftermarket')], db_index=True, default='brp', max_length=20, verbose_name='Каталог'),
        ),
        migrations.CreateModel(
            name='ArcticCatCatalogPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('dealer', 'Arctic Cat dealer')], max_length=40, verbose_name='Источник каталога')),
                ('supplier_article', models.CharField(max_length=100, verbose_name='Артикул Arctic Cat')),
                ('normalized_supplier_article', models.CharField(db_index=True, max_length=100)),
                ('source_description', models.CharField(max_length=255, verbose_name='Описание поставщика')),
                ('package_quantity', models.CharField(blank=True, max_length=80, verbose_name='Количество в упаковке поставщика')),
                ('dealer_price_usd', models.DecimalField(blank=True, decimal_places=2, max_digits=14, null=True, verbose_name='Цена дилера Arctic Cat, USD')),
                ('dealer_price_state', models.CharField(choices=[('known', 'Указана'), ('blank', 'Не указана'), ('zero', 'Нулевая, недоступна')], default='blank', max_length=10, verbose_name='Состояние цены дилера')),
                ('replacement_article', models.CharField(blank=True, max_length=100, verbose_name='Артикул замены Arctic Cat')),
                ('normalized_replacement_article', models.CharField(blank=True, db_index=True, max_length=100)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('part', models.OneToOneField(on_delete=django.db.models.deletion.PROTECT, related_name='arctic_cat_catalog_entry', to='catalog.parttype')),
            ],
            options={
                'verbose_name': 'Позиция Arctic Cat-каталога',
                'verbose_name_plural': 'Позиции Arctic Cat-каталога',
                'constraints': [models.UniqueConstraint(fields=('source', 'normalized_supplier_article'), name='uniq_arctic_cat_source_article')],
            },
        ),
    ]
