# Generated by Django 5.2.17 on 2026-09-06 13:14

import django.core.validators
import django.db.models.deletion
from decimal import Decimal
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0006_alter_partnumber_kind'),
        ('customers', '0002_customerperiodpaymentacknowledgement'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='OrderedPart',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article', models.CharField(max_length=100, verbose_name='Артикул (снимок)')),
                ('part_name', models.CharField(blank=True, max_length=255, verbose_name='Название (снимок)')),
                ('manufacturer_name', models.CharField(blank=True, max_length=120, verbose_name='Производитель (снимок)')),
                ('catalog_source', models.CharField(blank=True, max_length=40, verbose_name='Источник каталога (снимок)')),
                ('prepayment_rub', models.DecimalField(decimal_places=2, default=Decimal('0'), max_digits=12, validators=[django.core.validators.MinValueValidator(Decimal('0'))], verbose_name='Предоплата (₽)')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создан')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто оформил')),
                ('customer', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_parts', to='customers.customer', verbose_name='Клиент')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='ordered_parts', to='catalog.parttype', verbose_name='Деталь')),
                ('updated_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто изменил')),
            ],
            options={
                'verbose_name': 'Запчасть на заказ',
                'verbose_name_plural': 'Запчасти на заказ',
                'ordering': ['-created_at', '-id'],
                'constraints': [models.CheckConstraint(condition=models.Q(('prepayment_rub__gte', Decimal('0'))), name='orderedpart_prepayment_not_negative')],
            },
        ),
    ]
