# Generated by Django 5.2.15 on 2026-07-05 03:43

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='RestoreJob',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('run_id', models.CharField(max_length=64, verbose_name='Бэкап (run id)')),
                ('status', models.CharField(choices=[('pending', 'Ожидает'), ('verifying', 'Проверка бэкапа'), ('pre_backup', 'Pre-restore бэкап'), ('restoring', 'Восстановление'), ('migrated', 'Миграции применены'), ('completed', 'Завершено'), ('failed', 'Ошибка')], default='pending', max_length=20, verbose_name='Статус')),
                ('started_by_username', models.CharField(blank=True, max_length=150, verbose_name='Логин запустившего')),
                ('pre_restore_run_id', models.CharField(blank=True, max_length=64, verbose_name='Pre-restore бэкап')),
                ('log', models.TextField(blank=True, verbose_name='Журнал шагов')),
                ('error', models.TextField(blank=True, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Запущено')),
                ('finished_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершено')),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто запустил')),
            ],
            options={
                'verbose_name': 'Восстановление из бэкапа',
                'verbose_name_plural': 'Восстановления из бэкапов',
                'ordering': ['-created_at'],
            },
        ),
    ]
