# Generated by Django 5.2.15 on 2026-08-12 06:45

import django.core.validators
import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


def create_deployment_state(apps, schema_editor):
    DeploymentState = apps.get_model('operations', 'DeploymentState')
    DeploymentState.objects.using(schema_editor.connection.alias).get_or_create(pk=1)


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='DeploymentState',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('database_identity', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('business_generation', models.PositiveBigIntegerField(default=0, help_text='Консервативный счётчик принятых write-запросов.', validators=[django.core.validators.MinValueValidator(0)])),
                ('write_state', models.CharField(choices=[('normal', 'Обычная работа'), ('maintenance', 'Production только для чтения'), ('emergency_active', 'Автономная работа'), ('emergency_frozen', 'Автономная копия заморожена')], db_index=True, default='normal', max_length=24)),
                ('state_reason', models.CharField(blank=True, max_length=255)),
                ('state_changed_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'verbose_name': 'Состояние deployment',
                'verbose_name_plural': 'Состояние deployment',
            },
        ),
        migrations.RunPython(create_deployment_state, migrations.RunPython.noop),
        migrations.CreateModel(
            name='OfflineSession',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('planned', 'Плановый переход'), ('unplanned', 'Внезапная потеря связи')], max_length=12)),
                ('status', models.CharField(choices=[('active', 'Автономная работа'), ('freezing', 'Остановка записи'), ('export_failed', 'Ошибка экспорта'), ('frozen', 'Экспорт завершён'), ('eligible', 'Допустим controlled failback'), ('conflict', 'Обнаружен конфликт'), ('blocked', 'Возврат заблокирован')], db_index=True, max_length=20)),
                ('local_hostname', models.CharField(max_length=255)),
                ('instance_id', models.CharField(max_length=128)),
                ('base_backup_run_id', models.CharField(max_length=128)),
                ('base_backup_created_at', models.DateTimeField()),
                ('base_manifest', models.JSONField(default=dict, editable=False)),
                ('base_data_marker', models.JSONField(default=dict, editable=False)),
                ('base_media_sha256', models.CharField(blank=True, max_length=64)),
                ('base_app_commit', models.CharField(blank=True, max_length=64)),
                ('base_migration_fingerprint', models.CharField(max_length=64)),
                ('started_at', models.DateTimeField(auto_now_add=True)),
                ('ended_at', models.DateTimeField(blank=True, null=True)),
                ('final_backup_run_id', models.CharField(blank=True, max_length=128)),
                ('final_manifest', models.JSONField(default=dict, editable=False)),
                ('final_data_marker', models.JSONField(default=dict, editable=False)),
                ('failback_report', models.JSONField(default=dict, editable=False)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('started_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='offline_sessions_started', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-started_at'],
            },
        ),
        migrations.CreateModel(
            name='EmergencyAuditEvent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_type', models.CharField(db_index=True, max_length=64)),
                ('outcome', models.CharField(db_index=True, max_length=16)),
                ('actor', models.CharField(blank=True, max_length=150)),
                ('details', models.JSONField(default=dict, editable=False)),
                ('created_at', models.DateTimeField(auto_now_add=True, db_index=True)),
                ('session', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='audit_events', to='operations.offlinesession')),
            ],
            options={
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.AddConstraint(
            model_name='offlinesession',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['active', 'freezing', 'export_failed'])), fields=('instance_id',), name='uniq_unfinished_offline_session'),
        ),
    ]
