# Generated by Django 5.2.15 on 2026-08-12 08:00

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("operations", "0002_deploymentstate_offlinesession_emergencyauditevent_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="offlinesession",
            name="status",
            field=models.CharField(
                choices=[
                    ("active", "Автономная работа"),
                    ("freezing", "Остановка записи"),
                    ("export_failed", "Ошибка экспорта"),
                    ("frozen", "Экспорт завершён"),
                    ("eligible", "Допустим controlled failback"),
                    ("conflict", "Обнаружен конфликт"),
                    ("blocked", "Возврат заблокирован"),
                    ("completed", "Возврат подтверждён"),
                ],
                db_index=True,
                max_length=20,
            ),
        ),
    ]
