# Generated by Django 5.2.17 on 2026-09-14 16:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0004_deploymentstate_emergency_primary_authorization'),
    ]

    operations = [
        migrations.CreateModel(
            name='TelegramBotRuntime',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('last_update_id', models.BigIntegerField(default=0, verbose_name='Последнее обработанное обновление')),
                ('worker_id', models.CharField(blank=True, max_length=64, verbose_name='Экземпляр бота')),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Аренда до')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Запущен')),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний сигнал')),
                ('last_update_at', models.DateTimeField(blank=True, null=True, verbose_name='Последнее обновление Telegram')),
                ('bot_username', models.CharField(blank=True, max_length=64, verbose_name='Имя бота')),
                ('last_error', models.CharField(blank=True, max_length=255, verbose_name='Последняя ошибка')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='Время ошибки')),
            ],
            options={
                'verbose_name': 'Состояние Telegram-бота',
                'verbose_name_plural': 'Состояние Telegram-бота',
            },
        ),
    ]
