# Generated by Django 5.2.17 on 2026-09-16 14:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('operations', '0005_telegram_messaging'),
    ]

    operations = [
        migrations.CreateModel(
            name='MaxBotRuntime',
            fields=[
                ('id', models.PositiveSmallIntegerField(default=1, editable=False, primary_key=True, serialize=False)),
                ('worker_id', models.CharField(blank=True, max_length=64, verbose_name='Экземпляр бота')),
                ('lease_expires_at', models.DateTimeField(blank=True, null=True, verbose_name='Аренда до')),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Запущен')),
                ('heartbeat_at', models.DateTimeField(blank=True, null=True, verbose_name='Последний сигнал')),
                ('announce_requests_since', models.DateTimeField(blank=True, null=True, verbose_name='Объявлять заявки начиная с')),
                ('bot_username', models.CharField(blank=True, max_length=64, verbose_name='Имя бота')),
                ('last_error', models.CharField(blank=True, max_length=255, verbose_name='Последняя ошибка')),
                ('last_error_at', models.DateTimeField(blank=True, null=True, verbose_name='Время ошибки')),
            ],
            options={
                'verbose_name': 'Состояние MAX-бота',
                'verbose_name_plural': 'Состояние MAX-бота',
            },
        ),
    ]
