# Generated by Django 5.2.15 on 2026-06-29 17:07

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('catalog', '0003_parttype_partnumber_partbarcode_partcompatibility'),
        ('inventory', '0008_alter_stockmovement_movement_type'),
        ('procurement', '0002_landed_cost'),
        ('warehouse', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='InventoryCountDocument',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('number', models.CharField(editable=False, max_length=20, unique=True, verbose_name='Номер')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('completed', 'Проведён'), ('canceled', 'Отменён')], default='draft', max_length=20, verbose_name='Статус')),
                ('comment', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Проведён (когда)')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменён (когда)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
                ('scope_location', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.storagelocation', verbose_name='Ячейка (область сверки)')),
            ],
            options={
                'verbose_name': 'Документ инвентаризации',
                'verbose_name_plural': 'Документы инвентаризации',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='InventoryCountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('expected_quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Системное кол-во (снимок)')),
                ('counted_quantity', models.DecimalField(blank=True, decimal_places=3, max_digits=12, null=True, verbose_name='Фактическое кол-во')),
                ('unit_cost_rub', models.DecimalField(decimal_places=2, default=0, editable=False, max_digits=12, verbose_name='Себестоимость за ед. (₽)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('adjustment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='+', to='inventory.stockmovement', verbose_name='Движение корректировки')),
                ('batch_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='procurement.batchline', verbose_name='Строка партии')),
                ('count_document', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stocktaking.inventorycountdocument', verbose_name='Документ')),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='warehouse.storagelocation', verbose_name='Ячейка')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='+', to='catalog.parttype', verbose_name='Деталь')),
                ('stock_lot', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='count_lines', to='inventory.stocklot', verbose_name='Лот')),
            ],
            options={
                'verbose_name': 'Позиция инвентаризации',
                'verbose_name_plural': 'Позиции инвентаризации',
                'ordering': ['id'],
                'constraints': [models.UniqueConstraint(fields=('count_document', 'stock_lot'), name='uniq_countline_doc_lot'), models.CheckConstraint(condition=models.Q(('counted_quantity__isnull', True), ('counted_quantity__gte', 0), _connector='OR'), name='countline_counted_non_negative')],
            },
        ),
    ]
