# Generated by Django 5.2.15 on 2026-08-07 09:14

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_parttypeimage'),
        ('procurement', '0002_landed_cost'),
        ('stocktaking', '0002_seed_inventory_count_sequence'),
        ('warehouse', '0004_storagelocationrenamehistory'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='SectionRecount',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('section_code', models.CharField(db_index=True, max_length=60, verbose_name='Участок')),
                ('status', models.CharField(choices=[('draft', 'Черновик'), ('counting', 'Идёт пересчёт'), ('ready', 'Готов к применению'), ('applying', 'Применяется'), ('completed', 'Завершён'), ('canceled', 'Отменён'), ('failed', 'Ошибка')], db_index=True, default='draft', max_length=20, verbose_name='Статус')),
                ('operation_key', models.CharField(editable=False, max_length=64, unique=True, verbose_name='Ключ операции')),
                ('snapshot', models.JSONField(default=dict, editable=False, verbose_name='Исходный snapshot')),
                ('result', models.JSONField(default=dict, editable=False, verbose_name='Результат')),
                ('error_message', models.CharField(blank=True, editable=False, max_length=500, verbose_name='Ошибка')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True, verbose_name='Начат')),
                ('completed_at', models.DateTimeField(blank=True, null=True, verbose_name='Завершён')),
                ('canceled_at', models.DateTimeField(blank=True, null=True, verbose_name='Отменён')),
                ('failed_at', models.DateTimeField(blank=True, null=True, verbose_name='Ошибка (когда)')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='section_recounts', to=settings.AUTH_USER_MODEL, verbose_name='Кто создал')),
            ],
            options={
                'verbose_name': 'Пересчёт участка',
                'verbose_name_plural': 'Пересчёты участков',
                'ordering': ['-created_at', '-id'],
            },
        ),
        migrations.CreateModel(
            name='SectionRecountCell',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.PositiveSmallIntegerField(verbose_name='Порядок')),
                ('status', models.CharField(choices=[('not_started', 'Не начато'), ('counting', 'В работе'), ('completed', 'Пересчитана')], default='not_started', max_length=20, verbose_name='Статус')),
                ('counted_at', models.DateTimeField(blank=True, null=True)),
                ('location', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_recount_cells', to='warehouse.storagelocation')),
                ('recount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cells', to='stocktaking.sectionrecount')),
            ],
            options={
                'ordering': ['sequence', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SectionRecountLine',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('part_number', models.CharField(max_length=100, verbose_name='Артикул (снимок)')),
                ('quantity', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Факт')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('cell', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stocktaking.sectionrecountcell')),
                ('part_type', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_recount_lines', to='catalog.parttype')),
                ('recount', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lines', to='stocktaking.sectionrecount')),
            ],
            options={
                'ordering': ['cell__sequence', 'part_number', 'id'],
            },
        ),
        migrations.CreateModel(
            name='SectionRecountAllocation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.DecimalField(decimal_places=3, max_digits=12, verbose_name='Количество')),
                ('unit_cost_rub', models.DecimalField(decimal_places=2, editable=False, max_digits=12, verbose_name='Себестоимость (snapshot)')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('batch_line', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='section_recount_allocations', to='procurement.batchline')),
                ('line', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='allocations', to='stocktaking.sectionrecountline')),
            ],
        ),
        migrations.AddConstraint(
            model_name='sectionrecount',
            constraint=models.UniqueConstraint(condition=models.Q(('status__in', ['draft', 'counting', 'ready', 'applying'])), fields=('section_code',), name='uniq_active_section_recount'),
        ),
        migrations.AddConstraint(
            model_name='sectionrecountcell',
            constraint=models.UniqueConstraint(fields=('recount', 'location'), name='uniq_recount_cell'),
        ),
        migrations.AddConstraint(
            model_name='sectionrecountcell',
            constraint=models.UniqueConstraint(fields=('recount', 'sequence'), name='uniq_recount_sequence'),
        ),
        migrations.AddConstraint(
            model_name='sectionrecountline',
            constraint=models.UniqueConstraint(fields=('cell', 'part_type'), name='uniq_section_recount_part_cell'),
        ),
        migrations.AddConstraint(
            model_name='sectionrecountline',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gte', 0)), name='section_recount_qty_nonnegative'),
        ),
        migrations.AddConstraint(
            model_name='sectionrecountallocation',
            constraint=models.UniqueConstraint(fields=('line', 'batch_line'), name='uniq_section_recount_allocation'),
        ),
        migrations.AddConstraint(
            model_name='sectionrecountallocation',
            constraint=models.CheckConstraint(condition=models.Q(('quantity__gt', 0)), name='section_recount_alloc_positive'),
        ),
    ]
