# Generated by Django 5.2.15 on 2026-08-07 09:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktaking', '0003_sectionrecount_sectionrecountcell_sectionrecountline_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionrecount',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
    ]
