# Generated by Django 5.2.15 on 2026-08-07 12:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stocktaking', '0004_sectionrecount_updated_at'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionrecount',
            name='snapshot_fingerprint',
            field=models.CharField(blank=True, editable=False, max_length=64, verbose_name='Fingerprint snapshot'),
        ),
        migrations.AddField(
            model_name='sectionrecountallocation',
            name='lot_status',
            field=models.CharField(choices=[('receiving', 'На приёмке'), ('available', 'Доступен'), ('quarantine', 'Карантин'), ('written_off', 'Списан'), ('depleted', 'Исчерпан')], default='available', editable=False, max_length=20, verbose_name='Статус лота (snapshot)'),
        ),
    ]
