# Generated by Django 5.2.15 on 2026-08-11 16:48

from django.db import migrations, models


def backfill_recount_snapshots(apps, schema_editor):
    SectionRecountAllocation = apps.get_model(
        'stocktaking', 'SectionRecountAllocation'
    )
    SectionRecountLine = apps.get_model('stocktaking', 'SectionRecountLine')
    PartPreferredLocation = apps.get_model('inventory', 'PartPreferredLocation')

    allocations = list(
        SectionRecountAllocation.objects.select_related('batch_line').all()
    )
    for allocation in allocations:
        allocation.batch_quantity_snapshot = allocation.batch_line.quantity
        allocation.batch_updated_at_snapshot = allocation.batch_line.updated_at
    if allocations:
        SectionRecountAllocation.objects.bulk_update(
            allocations,
            ['batch_quantity_snapshot', 'batch_updated_at_snapshot'],
        )

    current_preferred = {
        preferred.part_type_id: {
            'location_id': preferred.location_id,
            'updated_at': preferred.updated_at.isoformat(),
        }
        for preferred in PartPreferredLocation.objects.all()
    }
    lines = list(SectionRecountLine.objects.select_related('recount').all())
    for line in lines:
        snapshot_preferred = {
            item['part_type_id']: {
                'location_id': item['location_id'],
                'updated_at': item['updated_at'],
            }
            for item in line.recount.snapshot.get('preferred', [])
        }
        line.preferred_snapshot = snapshot_preferred.get(
            line.part_type_id,
            current_preferred.get(line.part_type_id, {}),
        )
    if lines:
        SectionRecountLine.objects.bulk_update(lines, ['preferred_snapshot'])


class Migration(migrations.Migration):

    dependencies = [
        ('inventory', '0013_stocklocationlock'),
        ('stocktaking', '0005_sectionrecount_snapshot_fingerprint_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='sectionrecount',
            name='scope',
            field=models.CharField(
                choices=[('section', 'Участок'), ('cell', 'Ячейка')],
                db_index=True,
                default='section',
                max_length=20,
                verbose_name='Область пересчёта',
            ),
        ),
        migrations.AddField(
            model_name='sectionrecountallocation',
            name='batch_quantity_snapshot',
            field=models.DecimalField(
                decimal_places=3,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name='Количество партии (snapshot)',
            ),
        ),
        migrations.AddField(
            model_name='sectionrecountallocation',
            name='batch_updated_at_snapshot',
            field=models.DateTimeField(
                editable=False,
                null=True,
                verbose_name='Партия обновлена (snapshot)',
            ),
        ),
        migrations.AddField(
            model_name='sectionrecountline',
            name='preferred_snapshot',
            field=models.JSONField(
                default=dict,
                editable=False,
                verbose_name='Закреплённая ячейка при первом вводе',
            ),
        ),
        migrations.RunPython(
            backfill_recount_snapshots,
            migrations.RunPython.noop,
        ),
        migrations.AlterField(
            model_name='sectionrecountallocation',
            name='batch_quantity_snapshot',
            field=models.DecimalField(
                decimal_places=3,
                editable=False,
                max_digits=12,
                verbose_name='Количество партии (snapshot)',
            ),
        ),
        migrations.AlterField(
            model_name='sectionrecountallocation',
            name='batch_updated_at_snapshot',
            field=models.DateTimeField(editable=False, verbose_name='Партия обновлена (snapshot)'),
        ),
    ]
