# Generated by Django 5.2.15 on 2026-06-24 10:15

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0002_seed_units_vehicle_types'),
    ]

    operations = [
        migrations.CreateModel(
            name='PartType',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активен')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=200, verbose_name='Название')),
                ('tracking_mode', models.CharField(choices=[('serial', 'Поштучный'), ('bulk', 'Количественный')], default='serial', max_length=10, verbose_name='Режим учёта')),
                ('description', models.TextField(blank=True, verbose_name='Описание')),
                ('recommended_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Рекомендуемая цена')),
                ('min_price', models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True, verbose_name='Минимальная цена')),
                ('min_stock_level', models.DecimalField(decimal_places=3, default=0, max_digits=12, verbose_name='Минимальный остаток')),
                ('category', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='catalog.category', verbose_name='Категория')),
                ('manufacturer', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='catalog.manufacturer', verbose_name='Производитель')),
                ('unit', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='parts', to='catalog.unit', verbose_name='Единица')),
            ],
            options={
                'verbose_name': 'Вид детали',
                'verbose_name_plural': 'Виды деталей',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='PartNumber',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, verbose_name='Значение')),
                ('normalized_value', models.CharField(db_index=True, editable=False, max_length=100)),
                ('kind', models.CharField(choices=[('oem', 'OEM'), ('article', 'Артикул'), ('analog', 'Аналог'), ('internal_ref', 'Внутренний справочный')], default='oem', max_length=20, verbose_name='Тип')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Основной')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='numbers', to='catalog.parttype')),
            ],
            options={
                'verbose_name': 'Номер детали',
                'verbose_name_plural': 'Номера детали',
                'ordering': ['kind', 'value'],
            },
        ),
        migrations.CreateModel(
            name='PartBarcode',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.CharField(max_length=100, unique=True, verbose_name='Штрихкод')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='barcodes', to='catalog.parttype')),
            ],
            options={
                'verbose_name': 'Заводской штрихкод',
                'verbose_name_plural': 'Заводские штрихкоды',
                'ordering': ['value'],
            },
        ),
        migrations.CreateModel(
            name='PartCompatibility',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year_from', models.IntegerField(blank=True, null=True, verbose_name='Год с')),
                ('year_to', models.IntegerField(blank=True, null=True, verbose_name='Год по')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Комментарий')),
                ('vehicle_model', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='compatibilities', to='catalog.vehiclemodel', verbose_name='Модель техники')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='compatibilities', to='catalog.parttype')),
            ],
            options={
                'verbose_name': 'Совместимость',
                'verbose_name_plural': 'Совместимость',
                'constraints': [models.UniqueConstraint(fields=('part', 'vehicle_model', 'year_from', 'year_to'), name='uniq_part_model_years')],
            },
        ),
    ]
