# Generated by Django 5.2.15 on 2026-06-30 04:40

import apps.core.files
import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0003_parttype_partnumber_partbarcode_partcompatibility'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartTypeImage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.FileField(upload_to=apps.core.files.image_upload_to, verbose_name='Файл')),
                ('caption', models.CharField(blank=True, max_length=255, verbose_name='Подпись')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Главное фото')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('is_active', models.BooleanField(default=True, verbose_name='Активно')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='images', to='catalog.parttype')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='%(app_label)s_%(class)s_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Кто загрузил')),
            ],
            options={
                'verbose_name': 'Фото вида детали',
                'verbose_name_plural': 'Фото видов деталей',
                'ordering': ['sort_order', 'uploaded_at'],
                'abstract': False,
                'constraints': [models.UniqueConstraint(condition=models.Q(('is_active', True), ('is_primary', True)), fields=('part',), name='uniq_parttypeimage_primary_active')],
            },
        ),
    ]
