# Generated by Django 5.2.15 on 2026-08-22 20:52

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0004_parttypeimage'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartAnalog',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('note', models.CharField(blank=True, max_length=255, verbose_name='Примечание')),
                ('created_at', models.DateTimeField(auto_now_add=True, verbose_name='Создана')),
                ('analog', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='original_links', to='catalog.parttype', verbose_name='Аналог')),
                ('created_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто связал')),
                ('original', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analog_links', to='catalog.parttype', verbose_name='Исходная деталь')),
            ],
            options={
                'verbose_name': 'Связь аналога',
                'verbose_name_plural': 'Связи аналогов',
                'ordering': ['analog__name', 'pk'],
                'constraints': [models.UniqueConstraint(fields=('original', 'analog'), name='uniq_part_analog_pair'), models.CheckConstraint(condition=models.Q(('original', models.F('analog')), _negated=True), name='part_analog_not_self')],
            },
        ),
    ]
