# Generated by Django 5.2.15 on 2026-08-23 03:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0005_partanalog'),
    ]

    operations = [
        migrations.AlterField(
            model_name='partnumber',
            name='kind',
            field=models.CharField(choices=[('oem', 'OEM'), ('article', 'Артикул'), ('analog', 'Вспомогательный номер'), ('internal_ref', 'Внутренний справочный')], default='oem', max_length=20, verbose_name='Тип'),
        ),
    ]
