# Generated by Django 5.2.17 on 2026-09-11 07:15
#
# Schema only. Existing PartTypeImage uploads have no recorded provenance, so
# this migration deliberately creates no PublicPartPhoto rows: every
# historical photo stays non-public until a catalog manager publishes it.

import django.db.models.deletion
import uuid
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0009_partanalog_public_confirmation'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PublicPartPhoto',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('public_id', models.UUIDField(default=uuid.uuid4, editable=False, unique=True, verbose_name='Публичный ID')),
                ('status', models.CharField(choices=[('published', 'Опубликовано'), ('rejected', 'Не показывать')], max_length=12, verbose_name='Статус')),
                ('source', models.CharField(blank=True, choices=[('own', 'Собственное фото'), ('manufacturer', 'Фото производителя'), ('supplier', 'Фото поставщика')], max_length=20, verbose_name='Источник фото')),
                ('source_note', models.CharField(blank=True, max_length=255, verbose_name='Откуда фото (примечание)')),
                ('is_primary', models.BooleanField(default=False, verbose_name='Главное в каталоге')),
                ('sort_order', models.PositiveIntegerField(default=0, verbose_name='Порядок')),
                ('version', models.CharField(blank=True, max_length=16, verbose_name='Версия копий')),
                ('confirmed_at', models.DateTimeField(blank=True, null=True, verbose_name='Опубликовано')),
                ('rejected_at', models.DateTimeField(blank=True, null=True, verbose_name='Снято или отклонено')),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('confirmed_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто опубликовал')),
                ('part', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='public_photos', to='catalog.parttype', verbose_name='Деталь')),
                ('rejected_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL, verbose_name='Кто снял')),
                ('source_image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='public_decision', to='catalog.parttypeimage', verbose_name='Внутреннее фото')),
            ],
            options={
                'verbose_name': 'Фото для публичного каталога',
                'verbose_name_plural': 'Фото для публичного каталога',
                'ordering': ['-is_primary', 'sort_order', 'pk'],
            },
        ),
        migrations.CreateModel(
            name='PublicPartPhotoRendition',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('variant', models.CharField(choices=[('card', 'Карточка в поиске'), ('detail', 'Страница детали')], max_length=10, verbose_name='Вариант')),
                ('content_type', models.CharField(max_length=40, verbose_name='Тип')),
                ('data', models.BinaryField(verbose_name='Данные')),
                ('width', models.PositiveIntegerField(verbose_name='Ширина')),
                ('height', models.PositiveIntegerField(verbose_name='Высота')),
                ('byte_size', models.PositiveIntegerField(verbose_name='Размер, байт')),
                ('sha256', models.CharField(max_length=64, verbose_name='SHA-256')),
                ('photo', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='renditions', to='catalog.publicpartphoto', verbose_name='Фото')),
            ],
            options={
                'verbose_name': 'Копия публичного фото',
                'verbose_name_plural': 'Копии публичных фото',
            },
        ),
        migrations.AddIndex(
            model_name='publicpartphoto',
            index=models.Index(fields=['part', 'status'], name='public_photo_part_status_idx'),
        ),
        migrations.AddConstraint(
            model_name='publicpartphoto',
            constraint=models.CheckConstraint(condition=models.Q(models.Q(('status', 'published'), _negated=True), models.Q(models.Q(('source', ''), _negated=True), ('confirmed_at__isnull', False)), _connector='OR'), name='public_photo_published_has_provenance'),
        ),
        migrations.AddConstraint(
            model_name='publicpartphoto',
            constraint=models.CheckConstraint(condition=models.Q(('status', 'published'), ('is_primary', False), _connector='OR'), name='public_photo_primary_is_published'),
        ),
        migrations.AddConstraint(
            model_name='publicpartphoto',
            constraint=models.UniqueConstraint(condition=models.Q(('is_primary', True), ('status', 'published')), fields=('part',), name='uniq_public_photo_primary'),
        ),
        migrations.AddConstraint(
            model_name='publicpartphotorendition',
            constraint=models.UniqueConstraint(fields=('photo', 'variant'), name='uniq_public_photo_variant'),
        ),
    ]
