# Generated by Django 5.2.17 on 2026-09-12 07:46

from django.db import migrations, models


def set_rolling_provenance_default(apps, schema_editor):
    """Keep old PostgreSQL writers safe without issuing unsupported SQLite DDL."""
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE catalog_parttype "
            "ALTER COLUMN price_provenance SET DEFAULT 'unverified'"
        )


def drop_rolling_provenance_default(apps, schema_editor):
    if schema_editor.connection.vendor == "postgresql":
        schema_editor.execute(
            "ALTER TABLE catalog_parttype ALTER COLUMN price_provenance DROP DEFAULT"
        )


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_public_catalog_rollback_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='certified_price_rub',
            field=models.DecimalField(
                blank=True,
                decimal_places=2,
                editable=False,
                max_digits=12,
                null=True,
                verbose_name="Цена, подтверждённая расчётом (₽)",
            ),
        ),
        migrations.AddField(
            model_name='parttype',
            name='price_provenance',
            field=models.CharField(
                choices=[
                    ("formula_certified", "Подтверждена формулой"),
                    ("valid_manual_exception", "Подтверждённое ручное исключение"),
                    ("unverified", "Цена требует проверки"),
                    ("source_missing", "Нет собственного оптового источника"),
                    ("not_applicable", "Формула не применяется"),
                ],
                default="unverified",
                editable=False,
                max_length=32,
                verbose_name="Основание текущей цены",
            ),
        ),
        # A rolling application rollback can still issue an INSERT with the
        # pre-0012 column list.  Keep a database-level default until every
        # writer has the provenance-aware model; Django's model default alone
        # is not present in that old raw INSERT.
        migrations.RunPython(
            set_rolling_provenance_default,
            drop_rolling_provenance_default,
        ),
    ]
