# Generated by Django 5.2.17 on 2026-09-12 07:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0011_public_catalog_rollback_defaults'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='certified_price_rub',
            field=models.DecimalField(blank=True, decimal_places=2, editable=False, max_digits=12, null=True, verbose_name='Цена, подтверждённая расчётом (₽)'),
        ),
        migrations.AddField(
            model_name='parttype',
            name='price_provenance',
            field=models.CharField(choices=[('formula_certified', 'Подтверждена формулой'), ('valid_manual_exception', 'Подтверждённое ручное исключение'), ('unverified', 'Цена требует проверки'), ('source_missing', 'Нет собственного оптового источника'), ('not_applicable', 'Формула не применяется')], default='unverified', editable=False, max_length=32, verbose_name='Основание текущей цены'),
        ),
    ]
