# Generated by Django 5.2.17 on 2026-09-19 09:46

from django.db import migrations, models
from django.db.models import Value


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0012_parttype_certified_price'),
    ]

    operations = [
        migrations.AddField(
            model_name='parttype',
            name='search_name_compact',
            field=models.CharField(blank=True, db_default=Value(''), editable=False, max_length=200, verbose_name='Название для поиска без разделителей'),
        ),
        migrations.AddIndex(
            model_name='parttype',
            index=models.Index(fields=['search_name_compact'], name='parttype_name_compact_idx'),
        ),
    ]
