# Generated by Django 5.2.17 on 2026-09-21 10:22

import django.db.models.functions.text
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0015_compact_name_pattern_index'),
    ]

    operations = [
        migrations.AddConstraint(
            model_name='partbarcode',
            constraint=models.UniqueConstraint(django.db.models.functions.text.Lower('value'), name='uniq_partbarcode_value_ci'),
        ),
    ]
