# Generated by Django 5.2.17 on 2026-09-21

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0016_partbarcode_uniq_partbarcode_value_ci"),
    ]

    operations = [
        migrations.CreateModel(
            name="ManualPurchasePrice",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "purchase_price_rub",
                    models.DecimalField(
                        decimal_places=2,
                        max_digits=12,
                        verbose_name="Закупочная цена (₽)",
                    ),
                ),
                ("created_at", models.DateTimeField(auto_now_add=True)),
                ("updated_at", models.DateTimeField(auto_now=True)),
                (
                    "part_type",
                    models.OneToOneField(
                        on_delete=django.db.models.deletion.CASCADE,
                        related_name="manual_purchase_price",
                        to="catalog.parttype",
                        verbose_name="Деталь",
                    ),
                ),
            ],
            options={
                "verbose_name": "Закупочная цена ручной детали",
                "verbose_name_plural": "Закупочные цены ручных деталей",
                "constraints": [
                    models.CheckConstraint(
                        condition=models.Q(purchase_price_rub__gt=0),
                        name="manual_purchase_price_positive",
                    ),
                ],
            },
        ),
    ]
