# Generated by Django 5.2.17 on 2026-09-22 19:09

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('catalog', '0017_manualpurchaseprice'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='PartPhotoUploadAudit',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('source', models.CharField(choices=[('desktop', 'DenisStock'), ('telegram', 'Telegram')], max_length=12, verbose_name='Источник')),
                ('owner_operator_key', models.CharField(blank=True, max_length=32, verbose_name='Ключ владельца')),
                ('operation_type', models.CharField(blank=True, max_length=12, verbose_name='Тип операции')),
                ('operation_id', models.PositiveBigIntegerField(blank=True, null=True, verbose_name='Операция')),
                ('uploaded_at', models.DateTimeField(auto_now_add=True, verbose_name='Загружено')),
                ('image', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='upload_audit', to='catalog.parttypeimage', verbose_name='Фото')),
                ('uploaded_by', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='part_photo_uploads', to=settings.AUTH_USER_MODEL, verbose_name='Внутренний пользователь')),
            ],
            options={
                'verbose_name': 'Аудит загрузки фото детали',
                'verbose_name_plural': 'Аудит загрузок фото деталей',
                'indexes': [models.Index(fields=['source', 'uploaded_at'], name='part_photo_audit_src_idx')],
            },
        ),
    ]
