# Generated by Django 5.2.17 on 2026-09-23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0018_partphotouploadaudit"),
    ]

    operations = [
        migrations.AlterField(
            model_name="partphotouploadaudit",
            name="source",
            field=models.CharField(
                choices=[
                    ("desktop", "DenisStock"),
                    ("telegram", "Telegram"),
                    ("max", "MAX"),
                ],
                max_length=12,
                verbose_name="Источник",
            ),
        ),
    ]
