# Generated by Django 5.2.17 on 2026-09-25 07:00

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_partphotouploadaudit_max_source"),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name="PartAnalogEvidence",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "source_type",
                    models.CharField(
                        choices=[
                            ("manufacturer_catalog", "Каталог производителя"),
                            ("supplier", "Поставщик"),
                            ("import", "Импортированный файл"),
                            ("manual", "Оператор вручную"),
                            ("aftermarket_catalog", "Каталог аналогов"),
                            ("other", "Другое"),
                        ],
                        default="manual",
                        max_length=30,
                        verbose_name="Тип источника",
                    ),
                ),
                (
                    "source_name",
                    models.CharField(
                        blank=True, max_length=255, verbose_name="Название источника"
                    ),
                ),
                (
                    "external_source_id",
                    models.CharField(
                        blank=True,
                        max_length=120,
                        verbose_name="Идентификатор во внешнем источнике",
                    ),
                ),
                (
                    "note",
                    models.CharField(
                        blank=True, max_length=500, verbose_name="Примечание"
                    ),
                ),
                (
                    "source_price",
                    models.DecimalField(
                        blank=True,
                        decimal_places=2,
                        max_digits=14,
                        null=True,
                        verbose_name="Цена источника",
                    ),
                ),
                (
                    "source_currency",
                    models.CharField(
                        blank=True, max_length=8, verbose_name="Валюта источника"
                    ),
                ),
                (
                    "source_price_observed_at",
                    models.DateTimeField(
                        blank=True,
                        null=True,
                        verbose_name="Когда источник называл эту цену",
                    ),
                ),
                (
                    "created_at",
                    models.DateTimeField(auto_now_add=True, verbose_name="Добавлена"),
                ),
            ],
            options={
                "verbose_name": "Провенанс связи аналога",
                "verbose_name_plural": "Провенанс связей аналогов",
                "ordering": ["-created_at", "-pk"],
            },
        ),
        migrations.RemoveConstraint(
            model_name="partanalog",
            name="uniq_part_analog_pair",
        ),
        migrations.AddField(
            model_name="partanalog",
            name="relation_type",
            field=models.CharField(
                choices=[
                    ("analog", "Аналог"),
                    ("supersession", "Замена артикула"),
                    ("cross_reference", "Кросс-ссылка"),
                ],
                db_default=models.Value("analog"),
                default="analog",
                max_length=20,
                verbose_name="Тип связи",
            ),
        ),
        migrations.AddField(
            model_name="partanalog",
            name="verification_state",
            field=models.CharField(
                choices=[
                    ("unverified", "Не подтверждена"),
                    ("verified", "Подтверждена"),
                    ("rejected", "Отклонена"),
                ],
                db_default=models.Value("unverified"),
                default="unverified",
                max_length=20,
                verbose_name="Статус проверки",
            ),
        ),
        migrations.AddConstraint(
            model_name="partanalog",
            constraint=models.UniqueConstraint(
                fields=("original", "analog", "relation_type"),
                name="uniq_part_analog_pair",
            ),
        ),
        migrations.AddField(
            model_name="partanalogevidence",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                related_name="+",
                to=settings.AUTH_USER_MODEL,
                verbose_name="Кто добавил",
            ),
        ),
        migrations.AddField(
            model_name="partanalogevidence",
            name="relation",
            field=models.ForeignKey(
                on_delete=django.db.models.deletion.CASCADE,
                related_name="evidence",
                to="catalog.partanalog",
                verbose_name="Связь",
            ),
        ),
        migrations.AddConstraint(
            model_name="partanalogevidence",
            constraint=models.UniqueConstraint(
                fields=("relation", "source_type", "source_name", "external_source_id"),
                name="uniq_part_analog_evidence_source",
            ),
        ),
    ]
