# Generated by Django 5.2.17 on 2026-09-24 08:22

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0019_partphotouploadaudit_max_source"),
    ]

    operations = [
        migrations.AddField(
            model_name="parttype",
            name="is_oil",
            field=models.BooleanField(default=False, verbose_name="Масло"),
        ),
        migrations.AddField(
            model_name="parttype",
            name="oil_package_volume_l",
            field=models.DecimalField(
                blank=True,
                decimal_places=3,
                max_digits=8,
                null=True,
                verbose_name="Объём упаковки, л",
            ),
        ),
        migrations.AddConstraint(
            model_name="parttype",
            constraint=models.CheckConstraint(
                condition=models.Q(
                    models.Q(("is_oil", False), ("oil_package_volume_l__isnull", True)),
                    models.Q(("is_oil", True), ("oil_package_volume_l__gt", 0)),
                    _connector="OR",
                ),
                name="parttype_oil_package_volume_required_iff_oil",
            ),
        ),
    ]
