# Generated by Django 5.2.17 on 2026-09-25 07:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("catalog", "0021_partanalogevidence_and_more"),
    ]

    operations = [
        migrations.AddIndex(
            model_name="parttype",
            index=models.Index(
                fields=["is_public", "is_active", "id"],
                name="parttype_public_active_idx",
            ),
        ),
    ]
